🚀 2단계 - 배포하기
next-step/infra-subway-deploy pull request #1048
Opened 2022-12-04 14:29 UTC by wlroh

동규님 안녕하세요!
인프라공방 교육생 노웅래입니다~

2단계 미션 완료되어서 리뷰 요청드립니다

공통 설정은 application.properties에 모아두고
profile별로 설정이 필요한 부분들은 별도의 properties로 분리하고 보안으로 인해 public repo에 올라갈 수 없는 정보만 별도로 서브모듈로 빼서 구성해보았습니다

잘 부탁드립니다!

2022-12-04 17:15 UTC, brainbackdoor requested changes
1단계 미션에 피드백 남겨둔 부분이 있는데요~ 확인 바래요
좋은 밤 보내세요~

2022-12-04 17:15 UTC, brainbackdoor commented on README.md
> +- URL : https://subway.wlroh.p-e.kr
https://github.com/next-step/infra-subway-deploy/pull/1019#discussion_r1037353757

이전 PR에 피드백 남겨두었는데요. 확인 바래요~ 🙏🏻

2022-12-05 11:42 UTC, wlroh commented on README.md
> +- URL : https://subway.wlroh.p-e.kr
앗... 죄송합니다...! 바로 Merge되어서 피드백 확인을 못했습니다 ㅠㅠ
바로 접속할 수 있도록 ssh 비밀번호 제거해두었습니다~
.ssh/config 에도 접속정보 추가해두었습니다!

2022-12-05 11:55 UTC, brainbackdoor approved these changes
2단계 미션 진행하느라 고생하셨어요~ 👍🏻 
추가미션인 서브모듈도 잘 적용하셨네요~ 
좋은 밤 보내세요~

2022-12-05 11:56 UTC, merged