[2단계 - 서비스 배포하기]
next-step/infra-subway-deploy pull request #108
Opened 2021-06-23 12:51 UTC by oper912

안녕하세요 리뷰어님!

1단계 이후로 굉장히 오랜만에 2단계 리뷰 요청드리네요 :sweat_smile:
처음 해보는 것들이 많아서 시간이 꽤 오래 걸린거같아요!

reverse-proxy 용 인스턴스 생성하여 nginx를 docker로 띄우고 TLS 인증서 발급받아서 HTTPS 적용하였습니다
설정 파일도 나누어 보았고 flyway도 적용하여 local에서 확인해보았습니다
SonarLint와 MultiRun도 적용해보았습니다

리뷰 잘 부탁 드립니다~!

2021-06-24 01:18 UTC, JunilHwang requested changes
안녕하세요 순호님! 서비스 배포하기 미션 잘 진행해주셨네요 👍 
혹시 git 서브모듈은 일부로 제외하신걸까요?
이 부분만 확인 부탁드립니다 🙇‍♂️

2021-06-24 01:18 UTC, JunilHwang commented on README.md
> +- URL : https://oper912-infra-subway.p-e.kr
SSL 인증서 적용 잘 되었네요 👍

2021-06-24 01:18 UTC, JunilHwang commented on docker/db/mysql/init/init.sql
> +ALTER DATABASE migration DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
마지막에 개행을 한 번 해주세요!
관련 키워드: `EOF`

2021-06-24 01:18 UTC, JunilHwang commented on docker/docker-compose.yml
> +      - ./db/mysql/init:/docker-entrypoint-initdb.d
여기도 동일합니다!

2021-06-24 01:18 UTC, JunilHwang commented on src/main/resources/application-local.properties
> +#spring.flyway.baseline-version=1
미션 내용 보시면 properties는 sub repository로 관리하는 형태로 제안하고 있는데 혹시 일부로 main repository에 올려주신걸까요?

2021-06-24 01:18 UTC, JunilHwang commented on src/main/resources/application-prod.properties
> +logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
prod 구분 👍

2021-06-24 01:18 UTC, JunilHwang commented on src/main/resources/application-test.properties
> +spring.jpa.hibernate.ddl-auto=create
test에서는  h2 사용 👍

2021-06-24 01:18 UTC, JunilHwang commented on build.gradle
> +	runtimeOnly 'org.flywaydb:flyway-core:5.2.0'
flayway 적용 👍

2021-06-24 01:18 UTC, JunilHwang commented on README.md
>  ### 2단계 - 배포하기
- [x] 운영 환경 구성하기
  - [x] 웹 애플리케이션 앞단에 Reverse Proxy 구성하기
    - [x] 외부망에 Nginx로 Reverse Proxy를 구성
    - [x] Reverse Proxy에 TLS 설정
  - [x] 운영 데이터베이스 구성하기
- [x] 개발 환경 구성하기
  - [x] 설정 파일 나누기
    - [x] JUnit : h2, Local : docker(mysql), Prod : 운영 DB를 사용하도록 설정
  - [x] 데이터베이스 테이블 스키마 버전 관리
  - [x] SonarLint 설정하기
  - [x] MultiRun 설정하기

2021-06-24 01:18 UTC, JunilHwang commented on src/main/resources/application-local.properties
> +#spring.flyway.baseline-version=1
![image](https://user-images.githubusercontent.com/18749057/123187534-4ffc7600-d4d5-11eb-8c29-b202a3a2ff4f.png)

2021-06-25 18:09 UTC, oper912 commented
안녕하세요 리뷰어님! 
리뷰 재요청드립니다

피드백 주신 파일의 마지막 라인 개행 추가하였습니다

아래 코멘트 주신 서브모듈 이용하여 설정을 별도로 관리하는건 과제의 요구 사항 설명의 체크리스트에는 존재하지 않길래 따로 하진않았었는데:sweat_smile: 
피드백 주신김에 해보는게 좋을 거 같아 반영해보았습니다!
https://github.com/next-step/infra-subway-deploy/pull/108#discussion_r657557233

감사합니다~!

2021-06-26 09:28 UTC, JunilHwang approved these changes
안녕하세요 순호님! 피드백 반영 잘 해주셨네요 👍
인프라는 아무래도 네트워크 관련 지식을 많이 알아야해서, 코드보다 요구되는 도메인이 많다보니 쉽지 않았으리라 생각합니다 ㅎㅎ 그래도 잘 마무리해주셔서 다행입니다!
짧은 기간이었지만 잘 따라와주셔서 감사합니다. 나머지 미션도 끝까지 잘 마무리하길 기대하겠습니다! 수고하셨습니다 🙇‍♂️

2021-06-26 09:29 UTC, merged