[FKgk] week1-step2 배포하기
next-step/infra-subway-deploy pull request #1164
Opened 2023-02-12 16:14 UTC by FKgk

- 개발 운영 환경 분리 (subnet혹은 vpc도 분리하면 좋을 것 같습니다)
- 환경에 따른 spring 환경설정 분리 (설정파일에 익숙하지 않아서 분리에만 초점을 맞추었습니다)

2023-02-14 20:35 UTC, brainbackdoor requested changes
2단계 미션 진행하느라 고생하셨어요~ 
확인할 부분이 있어 Comment 남겨두었어요~ 
혹시 추가로 궁금한 점이 있으면 메시지 주세요~ 좋은 하루 보내세요~

2023-02-14 20:35 UTC, brainbackdoor commented on src/main/resources/application-local.properties
> +account.password = local
서버 들어가서 보니, application-prod.properties도 같은 내용이던데요.
2단계 요구사항은 was에서 내부망 디비를 바라보도록 구성하는 것까지가 요구사항이에요
위의 값들은 실습차원에서 적어둔 것뿐이니 본 미션에서는 제거하시면 됩니다.

2023-02-14 20:35 UTC, brainbackdoor commented on README.md
> +- URL : https://sample-subway.o-r.kr (dev: http://dev.sample-subway.o-r.kr)
- dev 서버의 역할은 무엇인가요?

2023-02-16 12:28 UTC, FKgk commented on src/main/resources/application-local.properties
> +account.password = local
내부망 바라보도록 변경했습니다!

2023-02-16 12:29 UTC, FKgk commented on README.md
> +- URL : https://sample-subway.o-r.kr (dev: http://dev.sample-subway.o-r.kr)
요구사항에 개발, 운영 환경 구성하기가 있어서 만들었는데요 환결 설정만 의미하는 거였군요
저기 서버에서 설정이나 nginx 등 실습하고 운영환경에 반영하는 방식으로 진행했습니다 삭제 하겠습니당!

2023-02-17 12:19 UTC, brainbackdoor commented
deploy.sh를 보니, 서버 중지 후 재실행할 때 프로세스가 없어서 에러가 나겠네요.
그리고 profile 옵션은 `-Dspring.profiles.active=prod` 입니다. 옵션이 적용되지 않는다는 에러가 나서 서버가 안뜨지 않았나요?

2023-02-17 12:20 UTC, brainbackdoor approved these changes
피드백 반영 잘해주셨네요~ 👍🏻 
한가지 확인할 부분이 있어 Comment 남겨두었어요~ 확인 바래요~
좋은 밤 보내세요~

2023-02-17 12:20 UTC, merged

2023-02-18 00:47 UTC, FKgk commented
![image](https://user-images.githubusercontent.com/40608930/219822097-b7014006-0d3e-4130-b324-b114eef72cd9.png)
저도 그런줄 알았는데요 intellij 에서 실행할떄도 `-Dspring.profiles.active=prod` 로 실행이 되었어요 
근데, 터미널에서 실행하면 저 옵션이 안 먹히고 `--spring.profiles.active=prod` 적용이 되었어요

2023-02-18 01:07 UTC, FKgk commented
계속 depoly.sh 테스트할 때, 프로세스가 있어서 잘 동작했나 봐요
해당 문제 부분 아래와 같이 수정했습니다 
```
        if [[ -n "$(pgrep -f ${FILE_NAME})" ]]
        then
                kill -2 $(pgrep -f ${FILE_NAME})
        fi
```
(`PID="$(pgrep -f ${FILE_NAME})"` 도 될 줄 알았는데, 안되네요)