[Mission4. 그럴듯한 서비스 만들기] 2단계 - 서비스 배포하기
next-step/infra-subway-deploy pull request #131
Opened 2021-07-04 09:28 UTC by gregolee

안녕하세요. 황준일 리뷰어님! 🙇 
네번째 미션 2단계 제출합니다! 적용하고 테스트하는데 다소 시간이 걸렸습니다 😢 
그래도 잘 배워서 적용하겠다는 마음으로 조급함보다는 평온할 수 있도록 노력했습니다! 😄 
고쳐야할 부분이나 개선할 부분이 있다면 말씀주시기 바랍니다! 🙇 
좋은 하루되세요!!

2021-07-05 07:38 UTC, JunilHwang requested changes
안녕하세요 재영님! 서비스 배포하기 진행 잘 해주셨네요 👍
다만 지금 TLS 인증서에 무언가 문제가 있는 것 같아요! 사이트 접속이 안되고 있네요 ㅠㅠ
그리고 git submodule도 사용해보면 어떨까요?

2021-07-05 07:38 UTC, JunilHwang commented on README.md
> +- URL : https://infra.gregolee.kro.kr/ (Production 환경으로 설정해둠)
지금 접속이 안되고 있네요 ㅠㅠ 다시 한 번 확인해주실 수 있을까요?

2021-07-05 07:38 UTC, JunilHwang commented on build.gradle
> +	implementation 'org.flywaydb:flyway-core'
flyway 적용 👍

2021-07-06 06:48 UTC, gregolee commented on README.md
> +- URL : https://infra.gregolee.kro.kr/ (Production 환경으로 설정해둠)
제가 SSL 적용을 제대로 적용한게 아니었습니다 😢
자물쇠가 보이도록 다시 조정하겠습니다! 🙇

2021-07-06 06:49 UTC, gregolee commented on build.gradle
> +	implementation 'org.flywaydb:flyway-core'
처음 써보는 것인지라 한참 해맸던 부분이었습니다 ㅠㅠ 
그래도 제대로 적용해보고 다음에도 잘 써보겠습니다!
칭찬 감사합니다!! 🙇 😄

2021-07-06 07:44 UTC, gregolee commented
안녕하세요. 황준일 리뷰어님! 🙇
과거에 SSL 적용되었다는 가정 하에 개발 작업을 했었기에 문제가 없었다 생각했습니다. 😢 
지금에서 돌아보면 참 부끄럽습니다. 😭 
그래도 제대로 알고 적용함을 배우고 다음으로 넘어가는 것이 옳았다고 생각합니다! 😄 😄 😄 
이번에도 좋은 피드백 남겨주셔서 감사합니다!! 🙇 🙇 🙇 🙇

2021-07-06 07:49 UTC, JunilHwang approved these changes
안녕하세요 재영님! 피드백 반영 잘 해주셨네요 👍 
인프라는 네트워크와 운영체제 관련 지식이 있어야 하다보니 (요구하는 도메인 지식이 많다보니..) 난이도가 좀 있는 편입니다 ㅎㅎ 오류를 찾아내기도 쉽지 않죠 ㅠㅠ 너무 추상적인 경우가 많아서..

그럼에도 불구하고 잘 진행해주셔서 감사합니다 🙇‍♂️

그럴듯한 서비스 만들기 미션은 여기서 마무리하겠습니다 😁
고생하셨습니다!

2021-07-06 07:49 UTC, merged