Step2 - 서비스 배포하기
next-step/infra-subway-deploy pull request #145
Opened 2021-11-20 07:40 UTC by devyonghee

안녕하세요 리뷰어님!!
저번에 질문 드린 내용대로 보안그룹은 최대한 서로 참조할 수 있도록 설정하였고
운영 코드들은 모두 `SonarLint` 를 적용하면서 수정하게 되었습니다. 
`MultiRun` 설정은 실제 적용한 것을 보여드릴 수 있는 방법이 없는 것 같아서 이미지로 첨부드리겠습니다.🙇‍♂️
설정 파일들은 모두 서브 모듈로 옮겼는데 필요하다면 `public` 으로 전환하도록 하겠습니다! 🤔

![image](https://user-images.githubusercontent.com/54215394/142718544-c2ffd160-e789-4220-87e8-1b75b67d48eb.png)

2021-11-21 05:00 UTC, nokchax requested changes
안녕하세요, 용희님 깔끔하게 구성해 주셨네요 💯 
한가지만 확인해 보시라고 코멘트 남겼는데 확인 부탁드립니다 :)

2021-11-21 08:50 UTC, devyonghee commented on .gitignore
> +docker/db/mysql/data/
안녕하세요 광현님 코멘트 진심으로 감사드립니다!!
제안해주신 컨셉이 스프링 설정 파일에서는 도메인 이름으로 접근하고 서버에서는 /etc/hosts 에 별칭을 정의하는 것이 맞을까요??
그러면 새로운 서비스 서버가 생길 때마다 사설ip 로 같은 설정을 반복해줘야 할 것 같은데 혹시 어떤 장점이 있을까요??
도메인 이름으로 접근하기 위한 거라면 Route53 을 통해 VPC 내에 private DNS 를 두는 방향은 혹시 어떻게 생각하시나요??

2021-11-22 00:07 UTC, nokchax commented on .gitignore
> +docker/db/mysql/data/
늦게 봤네요 ㅎㅎ 네 설정파일 내에서는 도메인 접근, 서버에서 hosts를 수정하여 별칭을 만들어 주는걸 의미했습니다.
장점이라 한다면, ip가 변경되었을때 코드 수정후 재배포를 하지 않아도 된다 정도에 설정 파일 내부에 ip정보를 숨길수 있다. 정도가 있겠네요, 말씀주신 방법이 훨씬 좋아보입니다 :) 그런데 해당 기능이 이번 실습계정에서 지원이 될지는 모르겠네요!

2021-11-22 05:17 UTC, devyonghee commented on .gitignore
> +docker/db/mysql/data/
코멘트 감사드립니다!!! 🙇‍♂️
설정 파일에서도 ip 가 아니라 도메인 이름으로 접근하여 한층 더 보안이 좋아질 수 있겠군요 👍👍
우선 제가 생각해본 방법대로 route53 설정을 살펴보려했더니 역시 권한이 없어서 불가능하네요 🥲
그래서 광현님께서 제안주신대로 /etc/hosts 별칭을 추가하여 
`jdbc:mysql://subwaydb:3306` 이렇게 접근하도록 수정했습니다!!😆

2021-11-22 10:27 UTC, nokchax approved these changes
안녕하세요, 용희님, 마지막 과제도 잘 진행해주셨습니다 💯 👏👏 
아직 수업듣기 전인데도 잘 구성해주셨네요 😮  이번 단계는 이만 마치겠습니다. :)
마지막까지 파이팅입니다 💪

2021-11-22 10:27 UTC, merged