feat: 2단계 요구사항 구현 완료
next-step/infra-subway-deploy pull request #146
Opened 2021-11-20 09:09 UTC by IW-MOON

안녕하세요 리뷰어님,
2단계 요구사항 구현 완료해서 PR 요청드립니다.

감사합니다. 😄

2021-11-20 12:52 UTC, leeyohan93 requested changes
안녕하세요 인우님 :)
2단계 요구사항에서 확인이 필요한 부분이 있는 것 같습니다
확인 부탁드릴게요 🙏

2021-11-20 13:05 UTC, IW-MOON commented on README.md
> +- URL : https://www.iw-moon.kro.kr/
reverse proxy는 구성했는데.. 고급버튼을 눌러 안전하지 않은 페이지로 돌아가기 버튼을 클릭하면 뜨더라구요~

2021-11-22 14:19 UTC, IW-MOON commented on README.md
>  ### 2단계 - 배포하기
빠뜨린 부분 추가 반영하였습니다!

2021-11-23 09:55 UTC, leeyohan93 approved these changes
인우님 미션을 잘 마무리 해주셨네요 💯
아직 강의 이전인데 미션 진행을 잘해주셨네요 👍 
다음 미션도 좋은 모습으로 완주하시리라 믿습니다.🔥
감사합니다.

2021-11-23 09:55 UTC, merged