Step1 - 서비스 구성하기
next-step/infra-subway-deploy pull request #209
Opened 2021-12-02 15:09 UTC by pageprologue

리뷰어님 안녕하세요😀
그럴듯한 서비스 만들기 미션에서 AWS를 처음 사용해 보았습니다.
처음엔 서버와 네트워크에 대해 부족한 점을 많이 느끼면서 막막했지만 그래도 차근차근 해보면서 성취감을 느껴볼 수 있었습니다!
인프라 정말 어렵지만 재밌기도 하네요~ 미션을 진행하면서 막히는 부분이 있었는데, 어떤 방향으로 풀어갈 수 있는지를 여쭤봤더니 그 이후부터는 좀 더 감이 잘 잡혔던 것 같습니다. 미션 진행하면서 네트워크 구성의 그림이 점점 그려지는 것 같아서 도움이 많이 되었습니다. 
질문을 주셔도 좋고, 부족한 점은 얼마든지 리뷰 부탁드립니다.
그럼 이번 미션 잘 부탁드리겠습니다.🙏

2021-12-03 10:53 UTC, nokchax requested changes
안녕하세요, 희진님! 그럴듯한 서비스 구성하기 주차 리뷰어 김광현입니다 🙇‍♂️ 
요구사항 모두 잘 만족해 주셨는데, 추가적으로 진행해 보셨으면 하는 것들이 있어 코멘트 남겼습니다.
확인후 재요청 부탁드릴게요, 추가적으로 궁금하신 사항은 코멘트나 DM으로 문의주세요 :)

2021-12-03 10:53 UTC, nokchax commented on README.md
> +
- [x] VPC 생성
  - [x] CIDR은 C class(x.x.x.x/24)로 생성. 이 때, 다른 사람과 겹치지 않게 생성
- [x] Subnet 생성
  - [x] 외부망으로 사용할 Subnet : 64개씩 2개 (AZ를 다르게 구성)
  - [x] 내부망으로 사용할 Subnet : 32개씩 1개
  - [x] 관리용으로 사용할 Subnet : 32개씩 1개
- [x] Internet Gateway 연결
- [x] Route Table 생성
- [x] Security Group 설정
  - [x] 외부망
    - [x] 전체 대역 : 8080 포트 오픈
    - [x] 관리망 : 22번 포트 오픈
  - [x] 내부망
    - [x] 외부망 : 3306 포트 오픈
    - [x] 관리망 : 22번 포트 오픈
  - [x] 관리망
    - [x] 자신의 공인 IP : 22번 포트 오픈
- [x] 서버 생성
  - [x] 외부망에 웹 서비스용도의 EC2 생성
  - [x] 내부망에 데이터베이스용도의 EC2 생성
  - [x] 관리망에 베스쳔 서버용도의 EC2 생성
  - [x] 베스쳔 서버에 Session Timeout 600s 설정
  - [x] 베스쳔 서버에 Command 감사로그 설정

요구사항 모두 잘 만족하셨습니다. 추가적으로 진행해 보셨으면 하는 것이 있어서 코멘트 남길게요!
1. 서브넷 name에 a,b,c,d와 같은 의미없는 네이밍 보다는 public private admin 과 같은 네이밍으로 알아보기 쉽게 해주세요
2. 이번 요구사항에는 없지만, 내부망의 서버에서 라이브러리등 설치를 위해 외부망에 접속할 필요가 있는데요, 이때 NatGateway를 사용해야 합니다. 자세한 설명은 강의 자료 망 분리하기 -> 5. 외부 네트워크와 연결하기 를 참고해주세요 :)
3.  퍼블릭 시큐리티 그룹에서 사용하지 않는 포트는 닫아주세요
4. 시큐리티 그룹 설정에서 source에 사설 ip를 사용해 주셨는데요, 그렇게 되면 서버가 교체 되었을 경우나 여러 서브넷에서 접근할 때, 매번 인바운드 규칙을 수정해줘야 합니다. 시큐리티 그룹을 소스로 지정하면 변화에 유연하게 대처할 수 있습니다 :)
5. 리뷰를 위해 bastion 시큐리티 그룹에 인바운드 규칙에 제 IP를 추가해 뒀습니다. 참고해주세요
6. 앱이 다운되어 있어 서버 접근이 안되고 있네요, 사용하신 명령어만으로는 서버가 꺼질 위험성이 있습니다. 강의 자료에도 있지만, nohup 그리고 `&` 명령어에 대해서 찾아보시길 바래요 :)
7. 배스쳔 서버에서 database 서버로 접근이 가능하게 해주세요
8. public 서버들과 database 서버에도 배스쳔 서버와 마찬가지로 타임아웃 설정, 감사로그 남기기 등 부가적인 설정을 해주시면, 이후에 과제 진행에 도움이 될거 같아요

2021-12-03 20:45 UTC, pageprologue commented on README.md
> +
1. ``pageprologue-public-web1``, ``pageprologue-public-web2``, ``pageprologue-admin``,  ``pageprolouge-private-db`` 이렇게 수정하였습니다!
    
2. Internal 라우팅 테이블에 NatGateway 설정하였습니다.
    
3. 전체 대역 ICMP와 HTTPS 포트는 닫았습니다. 80 포트는 도메인에서 사용해서 열어 두었는데요. 이 부분도 수정이 필요할까요~?
    
4. public-ip 보안 그룹을 생성해서 admin 보안 그룹에 추가했더니 잘 동작하지 않아서 기존에 했던대로 돌려둔 상태입니다. Security Group에서 다른 Security Group을 참조하는 방식이라고 이해했는데 적용이 잘 안되네요.. 제가 놓친 부분이 있을까요?
    
5. 네😀
    
6. 앗 이 부분을 잘 못봤네요..! 알려주셔서 감사합니다 :) 일반적으로 `nohup` 명령어를 사용할 때는 백그라운드 작업으로 실행하는 경우가 많기 때문에 뒤에`&`를 붙여서 백그라운드 실행이라는 것을 명시해 준다고 합니다.
    
7. bastion 서버에서 database 서버로 접근 되도록 수정하였습니다.
    
8. 다른 서버들에도 로그와 설정 추가하였습니다~😀

2021-12-05 04:13 UTC, nokchax commented on README.md
> +
3. 8080만 닫으시면 됐는데 ㅠ, ICMP는 학습하셨다면 상관 닫아도 상관없구요, 443은 다음 과정에서 다시 진행하시면 되니 문제없습니다.
4. 아래 스크린샷에서 선택을 시큐리티 그룹으로 하시면 되는데요, 아마 희진님께서 안되셨던 이유는 ec2 인스턴스가 사용하고 있는 보안 그룹이 새로 생성한 public-ip 보안 그룹이 아니여서 그런거 같아요. 보안 그룹을 변경하셨다면 인스턴스가 사용하는 보안그룹도 변경해 주셔야 합니다.
![image](https://user-images.githubusercontent.com/32362748/144733044-992f6bd9-ff4f-4fd4-b2bc-a7d281f4af40.png)

2021-12-05 04:14 UTC, nokchax approved these changes
안녕하세요, 희진님! 리뷰가 늦어져서 죄송합니다 ㅠ 🙇‍♂️ 라식 회복이 생각보다 더뎌서 늦었네요
피드백 잘 반영해 주셨습니다. 질문 주신 내용에 대해서는 답변 남겼어요 :)
이번 단계는 이만 머지 하겠습니다. 나머지는 다음 과정에 같이해보세요.

2021-12-05 04:14 UTC, merged

2021-12-05 09:42 UTC, pageprologue commented on README.md
> +
앗 그렇군요..! 저는 전체 대역으로 8080 포트 오픈해야 한다는 요구사항을 보고 8080을 그냥 두었습니다..! 이 부분은 다시 수정하도록 하겠습니다~ㅎㅎ