[Step2] 리뷰요청드립니다.
next-step/infra-subway-deploy pull request #217
Opened 2021-12-04 11:51 UTC by eedys1234

2021-12-04 13:38 UTC, slamdunk7575 requested changes
정환님~ 구성하시느라 고생하셨어요 👍
TLS 설정 부분 확인부탁드립니다.
조금만 더 힘내주세요~!

2021-12-04 13:38 UTC, slamdunk7575 commented on README.md
> +- URL : https://www.eedys-lee.p-e.kr/
<img width="377" alt="스크린샷 2021-12-04 오후 10 12 44" src="https://user-images.githubusercontent.com/15867808/144711366-94744756-3bf3-4fb3-a39d-4f55fde9f44a.png">

- [ ] Reverse Proxy에 TLS 설정
`TLS 설정` 확인부탁드립니다 🙏

2021-12-04 13:38 UTC, slamdunk7575 commented on src/main/resources/application-prod.properties
> +spring.profiles.active=/config/prod
프로퍼티 파일을 `submodule`로 분리해보셨네요 💯

2021-12-04 13:38 UTC, slamdunk7575 commented on src/main/resources/db/local/migration/V1.2__change_name.sql
> +alter table account change name account_name varchar(255);
`Flyway`를 통해 스키마 버전 관리 잘 해주셨네요 👍

2021-12-05 01:44 UTC, eedys1234 commented on README.md
> +- URL : https://www.eedys-lee.p-e.kr/
https://eedys-lee.p-e.kr/ 로 url 변경하였습니다!

2021-12-05 01:46 UTC, eedys1234 commented on src/main/resources/application-prod.properties
> +spring.profiles.active=/config/prod
직접적으로 submodule을 참조하는게 더 좋을까요??

2021-12-05 08:56 UTC, slamdunk7575 approved these changes
정환님~ 고생 많으셨습니다.
남은 미션도 꾸준히 진행하시고 끝까지 완주하시길 응원하겠습니다! 🎉

2021-12-05 08:56 UTC, slamdunk7575 commented on src/main/resources/application-prod.properties
> +spring.profiles.active=/config/prod
네 각 프로퍼티에 설정하셔도 좋을것 같아요~

(참고)
인터넷에서 private 서브넷에 접근 불가는 유지하면서 반대로 private에서 외부와 통신이 가능하도록 구성하는 방법도 있는데요.
나중에 여유있으실때 `NAT Gateway` or `NAT 인스턴스`에 대해 찾아보시면 좋을 것 같아요 :)

2021-12-05 08:57 UTC, merged

2021-12-05 08:58 UTC, slamdunk7575 commented on src/main/resources/application-prod.properties
> +spring.profiles.active=/config/prod
네 각 프로퍼티에 설정하셔도 좋을것 같아요~

(참고)
인터넷에서 private 서브넷에 접근 불가는 유지하면서 반대로 private에서 외부와 통신이 가능하도록 구성하는 방법도 있는데요.
나중에 여유있으실때 `NAT Gateway` or `NAT 인스턴스`에 대해 찾아보시면 좋을 것 같아요 :)