2단계
next-step/infra-subway-deploy pull request #248
Opened 2021-12-27 14:50 UTC by HyunAh-iia

안녕하세요 :)
2단계 미션 PR 요청 드립니다.
미션을 진행하면서 궁금했던 거, 혹은 리뷰하실 때 참고하실 만한 사항들 나열했습니다.
감사합니다.
- 데이터베이스(도커)가 설치되는 EC2는 private subnet에 생성되어 인터넷 게이트웨이가 연결되어 있지 않았습니다. 그래서 임시로 퍼블릭으로 열어놓고 도커 의존성을 설치한 후에 다시 프라이빗으로 변경하였습니다. 최초 설정을 위한 일회성 작업이라 NAT 설정은 하지 않았습니다 :) 이렇게 진행하면 될까요?
- 실행환경별 프로파일 설정을 위해 application*.yml 파일을 활용했습니다. 이 중 prod 제외한 설정들은 개발팀내에 자유롭게 공유되어도 될 것이라 판단하고, prod 설정파일만 별도 저장소에 생성했습니다. 확인을 위해 저장소는 퍼블릭으로 열어두었습니다.
- 웹서버에 배포는 하지 않았는데, 만약 해야한다면 jar 파일로 빌드 후 `java -jar -Dspring.profiles.active=prod [jar파일명]` 명령어로 실행시키겠습니다!

2021-12-28 13:20 UTC, jaeyeonling requested changes
미션을 잘 진행해주셨어요 👍 
소소한 코멘트 남겨두었으니 확인 부탁드릴게요~

2021-12-29 00:49 UTC, hannah628 commented on README.md
> +- URL : [http://hyunahiia.웹.한국:8080](http://hyunahiia.xn--yq5b.xn--3e0b707e:8080/)
아하 :) 넵넵 알겠습니다!

2021-12-29 00:49 UTC, hannah628 commented on .gitmodules
> +[submodule "src/main/resources/config"]
답변 감사해요

2021-12-29 09:04 UTC, hannah628 commented on README.md
> +- URL : [http://hyunahiia.웹.한국:8080](http://hyunahiia.xn--yq5b.xn--3e0b707e:8080/)
https://hyunahiia.xn--yq5b.xn--3e0b707e:8080/ 접속 시 443으로 리다이렉트 되도록 했습니다 :)

2021-12-30 12:29 UTC, jaeyeonling approved these changes
미션을 잘 진행해주셨습니다 👍 
코멘트 반영하시느라 고생 많으셨어요 😄

2021-12-30 12:29 UTC, merged