1주차 2단계 미션 수행
next-step/infra-subway-deploy pull request #321
Opened 2022-03-18 20:15 UTC by joel-you

안녕하세요. 동규님 새벽에 PR을 올리게 되었습니다.

Flyway 세팅하는 거에서 많이 시간을 날리게 되었네요 ..

이번에 문의드릴 사항은, git submodule 기능 관련인데요.
추가 되있는 만큼 진행하려 노력하였지만, 해당 not found repo 가 계속 뜨네요..

제 컴퓨터에 global username, useremail이 안잡혀서 그런건지, 혹시 해결방법을 아실까요?

2022-03-19 07:39 UTC, brainbackdoor requested changes
2단계 미션 잘 진행해주셨네요.
몇가지 확인할 부분이 있어 Comment 남겨두었어요~
주말 잘 보내세요!

2022-03-19 07:39 UTC, brainbackdoor commented on src/main/resources/config/application-prod.properties
> +spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
운영환경에 코드가 최신화되지 않아서 현재 was 는 운영 디비를 바라보고 있지 않네요.

2022-03-19 07:39 UTC, brainbackdoor commented on src/main/resources/config/application-prod.properties
> +spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
`spring.jpa.hibernate.ddl-auto=validate` 운영 디비를 사용할 경우 명시적으로 옵션을 추가하는 것은 어떨까요

2022-03-19 07:43 UTC, brainbackdoor commented
아, 추가로 submodule 이 not found 가 뜬다면 보통 권한 문제입니다.
secret 설정이 이슈인데요. 혹시 github 계정을 여러개 사용하신다면, secret credential 을 추가하더라도 파일 관리가 좀 까다로워서 추후에 github action 등 서드파티를 사용할 때 설정 문제로 헤매실 수 있어요.
소스트리나 Intellij 의 github 에서 계정정보를 관리하는걸 추천드립니다.

github 계정을 하나 쓰고 있는데도 문제라면, 작년 중반부부터 적용된 정책 때문일 가능성이 높아요 personal access token 등록하고 진행하시면 되어요. 관련해서는 구글링해보시면 포스팅이 많이 나옵니다.

2022-03-19 13:37 UTC, joel-you commented on src/main/resources/config/application-prod.properties
> +spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
> https://github.com/next-step/infra-subway-deploy/pull/321/files#r830453102
해당건에 대해선 추가해놧스빈다.



> 운영환경에 코드가 최신화되지 않아서 현재 was 는 운영 디비를 바라보고 있지 않네요.

이 건에 대해서도,  다시 최신화 해놓았습니다.

2022-03-20 15:14 UTC, joel-you commented
서브모듈 적용도 다시 했습니다.
아무래도 git 과 친하질 않아서 제가 실수한 부분이 있던 것 같네요.

다시 차근차근 적용을해보니 문제없이 적용이 되네요. ㅠㅠ

2022-03-20 22:31 UTC, brainbackdoor approved these changes
피드백 잘 반영하셨네요! 👍🏻 
이만 머지할게요~ 이번 주도 파이팅입니다! 💪🏻
한 주 잘 보내세요~

2022-03-20 22:31 UTC, merged