Chapter 1-2: tls 적용하기
next-step/infra-subway-deploy pull request #322
Opened 2022-03-19 03:04 UTC by com8599

- [ ] tls 적용하기
- [ ] 각 배포환경에 따른 properties 적용 확인
- [ ] 데이터베이스 관리하기
- [ ] 설정 별도로 관리하기
- [ ] 정적테스트(SonarLint)
- [ ] 로컬테스트(MultiRun)

2022-03-19 08:00 UTC, brainbackdoor requested changes
2단계 미션 진행하느라 고생하셨어요~ 
몇가지 확인할 부분이 있어 피드백 남겨두었는데요.
확인해보시고, 궁금한 점 있으면 메시지주세요~ 
주말 잘 보내세요!

2022-03-23 07:22 UTC, com8599 commented on README.md
> +- com8599-internal = 192.168.100.128/27
내부망의 db로 변경 완료하였습니다!

2022-03-23 07:23 UTC, com8599 commented on README.md
> +- URL : https://public1.com8599.p-e.kr/
인증서가 설치된 도메인으로 옮겼습니다

2022-03-23 07:24 UTC, com8599 commented on src/main/resources/application-local.properties
> +server.port=80
넵 수정완료하였습니다!

2022-03-24 10:51 UTC, brainbackdoor requested changes
2단계 미션 잘 진행하셨네요! 👍🏻 
몇가지 체크할게 있어서 피드백 남겼어요~ 확인 부탁드려요 🙏🏻

2022-03-24 10:51 UTC, brainbackdoor commented on src/main/resources/application-prod.properties
> +spring.datasource.url=jdbc:mysql://192.168.100.145:3306/subway
혹시 internal 에 3306 포트에 대해 any open 인 이유가 있을까요?

2022-03-24 10:51 UTC, brainbackdoor commented on src/main/resources/application-prod.properties
> +spring.datasource.url=jdbc:mysql://192.168.100.145:3306/subway
bastion 서버 22, 80번 포트에 대해 any open 인 이유가 있을까요?

2022-03-24 22:58 UTC, jiyounglee-gloud commented on src/main/resources/application-prod.properties
> +spring.datasource.url=jdbc:mysql://192.168.100.145:3306/subway
제가 회사에서 vpn사용이 잦아서 설정해두었으나 모두 지정으로 바꾸겠습니다! 감사합니다!

2022-03-25 11:44 UTC, brainbackdoor approved these changes
피드백 반영 확인했어요~
2단계 미션 진행하시느라 고생하셨어요! 👍🏻

2022-03-25 11:44 UTC, merged