docs: step1 망분리하기
next-step/infra-subway-deploy pull request #377
Opened 2022-04-21 00:07 UTC by bluewow

망분리하기 PR 요청드립니다! 

![image](https://user-images.githubusercontent.com/16996054/164344113-f4221174-7873-47c5-89e0-8fd9fc2789dd.png)
bastion 을 통해 shell 에 접속하고 있으며, 다른 public 망은 8080 만 열어두었습니다

질문1
- 외부망으로 subnet 을 2개를 만들었는데 하나의 큰 subnet 이 아닌 2개를 만든 이유가 궁금합니다

질문2
- Route Table 생성부분에서 VPC 생성할때 기본적으로 라우팅 테이블이 생기는데 새로 만들지 않고 사용해도 될까요?

질문3
- Bastion 에 외부에서 접속하기위해 private 라우팅 테이블을 인터넷게이트웨이에 묶었는데 올바른 작업인가요?

2022-04-21 10:44 UTC, brainbackdoor requested changes
1단계 미션 진행하느라 고생하셨어요! 
몇가지 피드백 남겨두었는데, 확인 부탁드려요~ 🙏🏻

2022-04-21 10:44 UTC, brainbackdoor commented on README.md
> +- 대역 : 192.168.9.xxx
internal 망도 인터넷망과 연결되어 있네요. NAT gateway 를 활용하여 내부망 -> 인터넷망 연결만 가능하도록 구성해보시겠어요?

2022-04-21 10:44 UTC, brainbackdoor commented on README.md
> +- 대역 : 192.168.9.xxx
db 의 경우 3306 포트가 any open 되어 있네요. 정책을 조정해보시겠어요?

2022-04-21 10:44 UTC, brainbackdoor commented on README.md
> +- 대역 : 192.168.9.xxx
nginx, db 의 경우 22번 포트에 대해 any open 되어 있는데요. 이 부분은 제거해둘게요

2022-04-21 12:43 UTC, bluewow commented on README.md
> +- 대역 : 192.168.9.xxx
1. 보안그룹 소스설정시 subnet name 으로 찾을수 없을까요? ip 를 직접 타이핑하려니 창을 하나 띄어서 비교하게 됩네요

2. 미션2단계의 nginx 설정중이라 EC2-bluewow-web 의 보안그룹에 임시 규칙을 추가했습니다 (8080 포트를 anyone 으로)

2022-04-21 12:45 UTC, bluewow commented on README.md
> +- 대역 : 192.168.9.xxx
![image](https://user-images.githubusercontent.com/16996054/164460887-785814d1-7c6d-4bef-b9ce-6588515451b5.png)
대략적인 플로우입니다

2022-04-21 15:58 UTC, bluewow commented on README.md
> +- 대역 : 192.168.9.xxx
도메인 등록하였습니다 http://www.infraway.kro.kr:8080/

2022-04-22 15:45 UTC, brainbackdoor commented on README.md
> +- 대역 : 192.168.9.xxx
안녕하세요~ 보안그룹 설정시 서브넷을 대상으로 지정할 수는 없어요. 다만, 보안그룹을 참조를 걸 수는 있어요.
가령 bastion 서버가 SG-bastion 보안그룹에 속해 있다면, web 서버의 보안그룹 SG-web 에서 22 포트에 대해 SG-bastion 보안 그룹을 허용하겠다고 설정할 수 있어요.

2022-04-22 15:46 UTC, brainbackdoor approved these changes
피드백 반영 잘해주셨네요! 👍🏻 
1단계는 여기서 머지할게요~

2022-04-22 15:46 UTC, merged