[1단계] 서비스 구성하기
next-step/infra-subway-deploy pull request #39
Opened 2021-06-12 06:29 UTC by LenKIM

안녕하세요. 이번 우테코Pro 에 참여하게 된 김정규입니다.

확인 중 궁금하신 부분있으시면 자유롭게 코멘트 부탁드리겠습니다.

감사합니다.

2021-06-12 14:22 UTC, ssosso requested changes
정규님~ 안녕하세요:)
늦게 피드백 드려 죄송합니다ㅠ 확인 부탁드립니다!

2021-06-12 14:22 UTC, ssosso commented on README.md
> +  - 내부망 서브넷 : 172.22.1.128/27
내부망에 생성해야 하는 EC2가 외부망에 생성되어 있는거 같아요~ (i-074019f08e73166f0)
확인 부탁드립니다~

2021-06-13 03:50 UTC, LenKIM commented on README.md
> +  - 내부망 서브넷 : 172.22.1.128/27
네! 확인하겠습니다!

2021-06-13 04:12 UTC, LenKIM commented
에고, 확인해본 결과 말씀주신것 처럼 잘못 EC2가 설정되어있음을 발견했습니다. 해당 인스턴스 재생성후 설정했습니다 : )

피드백 다시 재요청하겠습니다!

2021-06-13 05:05 UTC, ssosso approved these changes
정규님~ 새로 생성해주신 내부망 EC2 확인하였습니다~:)
다음 단계 진행 부탁드립니다~

2021-06-13 05:05 UTC, merged

2021-06-13 05:49 UTC, LenKIM commented
감사합니다 : )