Step1-서비스 구성하기
next-step/infra-subway-deploy pull request #436
Opened 2022-05-29 11:00 UTC by cyr9210

안녕하세요.
그럴듯한 서비스 만들기 1단계 서비스 구성하기 리뷰 요청드립니다.
감사합니다.

2022-05-30 13:55 UTC, chae-yh requested changes
안녕하세요 용락님! 서비스 구성하기 리뷰를 맡은 채영훈이라고 합니다!
전체적으로 서비스 잘 구성해주셨습니다 👍 다만 확인이 필요한 부분이 있어 코멘트 드리니 한번 확인 부탁드립니다

감사합니다 : )

2022-05-30 13:55 UTC, chae-yh commented on README.md
> +http://nextstep.devbong.com:8080
전체적으로 잘 구성해주셨습니다 👍
EC2는 public으로 된 것 하나가 안보이는데 해당 서버도 구성되면 좋을 것 같습니다!

- CIDR 구성 [O]
- 서브넷 구성 [O]
- 라우팅 테이블 [O]
- 인터넷 게이트웨이 [O]
- 보안그룹 [O]
- 호스팅 한 url로 접근[O]

2022-05-30 13:55 UTC, chae-yh commented on README.md
> +- management : 192.1.1.160/27
batsion 서버로 보이는데 전달 주신 pem 키로 접근이 안됩니다...ㅠ
접근 서버 : cyr9210-ec2-management
보안 규칙 : sgr-056ffcfab5ceb145a (reviewer)
사용 pem 키 : cyr9210.pem
한번 확인 부탁드립니다!

2022-05-31 16:31 UTC, cyr9210 commented on README.md
> +http://nextstep.devbong.com:8080
public2 추가하였습니다.!

2022-05-31 17:39 UTC, chae-yh approved these changes
용락님 안녕하세요! 피드백 잘 반영해주셨습니다 👍 

다음 미션 진행 부탁드립니다 : )

2022-05-31 17:39 UTC, merged