Step2 - 서비스 배포하기
next-step/infra-subway-deploy pull request #463
Opened 2022-06-02 13:58 UTC by limwoobin

안녕하세요 리뷰어님 2단계 리뷰 요청드립니다!

그리고 1단계때 사용하던 domain 은 2단계 미션 진행하면서
limwoobin-subway.p-e.kr -> woo.subway-limwoobin.p-e.kr 로 변경하게 되어 기존 도메인은 삭제했습니다.
그래서 변경된 도메인에 TLS 적용하게 되었습니다!

2022-06-03 17:04 UTC, oper912 requested changes
안녕하세요 우빈님 :)
2단계도 구성 잘해주셨네요 👍

다만 현재 외부망 SG가 과도하게 오픈되어있는 것 같은데 
이 부분만 재확인 하셔서 리뷰 다시 요청 부탁드립니다 🙏

2022-06-04 06:40 UTC, limwoobin commented
> 안녕하세요 우빈님 :) 2단계도 구성 잘해주셨네요 👍
> 
> 다만 현재 외부망 SG가 과도하게 오픈되어있는 것 같은데 이 부분만 재확인 하셔서 리뷰 다시 요청 부탁드립니다 🙏

안녕하세요 순호님 코멘트 받고 궁금한점 몇가지 질문드리려합니다
외부망 SG 가 과도하게 오픈되어있다는거는 TLS 가 적용되었음에도 불구하고 80 port 가 열려있다는 말씀으로 이해했습니다.
제가 이해한게 맞을까요??

2022-06-04 06:41 UTC, limwoobin commented on src/main/resources/application-prod.properties
> +spring.jpa.properties.hibernate.show_sql=true
prod 설정에서 어디가 부담스러운지 조금 더 명확하게 설명해주실수 있으실까요?ㅠㅜ
저는 혹시나 운영에서 ddl-auto create or create-drop 인줄알고 놀랬는데 그 부분은 아니어서
아직 감이 안잡히네요... 혹시 로그에 관련이 있을까요??

2022-06-04 06:48 UTC, limwoobin commented
> > 안녕하세요 우빈님 :) 2단계도 구성 잘해주셨네요 👍
> > 다만 현재 외부망 SG가 과도하게 오픈되어있는 것 같은데 이 부분만 재확인 하셔서 리뷰 다시 요청 부탁드립니다 🙏
> 
> 안녕하세요 순호님 코멘트 받고 궁금한점 몇가지 질문드리려합니다 
reverse proxy 가 있음에도 불구하고 8080port 가 오픈되어있어서 과도하게 오픈되어있다고 말씀하신것같은데
제가 이해한게 맞을까요??

2022-06-05 07:10 UTC, oper912 approved these changes
안녕하세요 우빈님 :)
명확하게 피드백을 드리지 못한 것 같은데 
외부망 SG의 인바운드 규칙 22번 포트가 모든 IP대역대에 허용되고 있어서 말씀드린거였어요 🙂
주말에도 미션 진행하시느라 고생이 많으십니다 다음 단계 진행해주세요!

2022-06-05 07:10 UTC, merged

2022-06-05 07:47 UTC, limwoobin commented
> 

치명적인 부분을 놓치고있었군요 ㅠㅜ 감사합니다