Step2 - 서비스 배포하기
next-step/infra-subway-deploy pull request #518
Opened 2022-06-06 14:30 UTC by kmmin78

안녕하세요, 영훈님! 🙇‍♂️

4주차 그럴듯한 서비스 만들기 미션의 1단계 - 서비스 배포하기 PR 드립니다!

기본 요구사항을 우선으로 진행했습니다!

이번 리뷰도 잘부탁드립니다. 🙂

2022-06-07 14:37 UTC, chae-yh requested changes
민성님 안녕하세요! 서비스 배포하기 인프라 구성도 잘 해주셨습니다 👍 
다만 바로 merge하기에는 조금 더 고민해보시면 좋을만한 내용이 있어 코멘트 드리니, 확인 부탁드립니다.

감사합니다 : )

2022-06-07 14:37 UTC, chae-yh commented on README.md
>  ### 2단계 - 배포하기
이번 스텝에서 추가로 확인하면 좋을만한 내용은 아래와 같습니다.

- flyway
- sonarlint
- multirun

sonarlint와 mulitrun의 경우는 사용하시는 IDE에서 설정하시면 되는 부분이라 따로 확인은 어렵습니다만, 한 번 적용해보시기를 추천드립니다.
현재 운영 DB에 데이터가 이미 적재되어 있는 상태이기 때문에 운영 DB에 flyway적용은 어려워보입니다만, 로컬이나 테스트 환경에서 flyway 적용을 테스트 해보는 것도 좋은 공부가 될 것 같습니다.
이 부분은 추가적으로 확인하면 좋을만한 내용이기에 필수 적용 내용은 아닙니다!

2022-06-08 12:21 UTC, kmmin78 commented on README.md
> +    - ip address : 43.200.69.208:8080
두 서버 모두 WAS 서버의 같은 역할을 하고 있으므로, WAS를 나타내는 PREFIX를 붙여서 WAS_SERVER_{A|B} 로 하겠습니다!

2022-06-08 12:26 UTC, kmmin78 commented on README.md
> +  - JUnit : h2, Local : docker(mysql), Prod : 운영 DB를 사용하도록 설정
앗...
docker run -d -p 3306:3306 brainbackdoor/data-subway:0.0.1 를 통해서 가져왔는데, 데이터가 따로 없었습니다.
혹시 다른 이미지를 사용해야되는 걸까요?? 🧐

2022-06-08 12:33 UTC, kmmin78 commented on README.md
> +  - JUnit : h2, Local : docker(mysql), Prod : 운영 DB를 사용하도록 설정
repository를 찾아보니 0.0.3 버전이 존재하는군요! 적용했더니 데이터가 정상적으로 출력됐습니다 ㅎㅎ

2022-06-08 15:16 UTC, kmmin78 commented on README.md
>  ### 2단계 - 배포하기
말씀하신 3개 내용 모두 로컬에 적용해봤습니다!
아직 능숙하게 사용할 수준은 아니지만, 수준이 올라가면 상당히 편리할 것 같다는 생각이 드네요 😊

2022-06-08 15:20 UTC, kmmin78 commented on src/main/resources/application-prod.properties
> +spring.datasource.password=masterpw
서브모듈을 적용해봤는데요!
제가 초기에 설정을 잘못한 건지, 자꾸 서브모듈의 경로가 src/main/resources/config/config 에 잡히게 되네요... 🥲
서브모듈을 제거했다가 다시 적용해도 똑같은 현상이 발생해서 일단은 그대로 유지한 상황입니다.
이대로는 어플리케이션에서 설정파일을 못읽어들여서, 어떻게 해야할 지 고민입니다...
혹시 원인을 알고 계실까요?

2022-06-09 08:24 UTC, chae-yh commented on src/main/resources/application-prod.properties
> +spring.datasource.password=masterpw
우선 민성님의 private repository에 올라간 설정파일을 확인해보면 좋을 것 같습니다. 혹시 해당 프로퍼티 파일이 config 디렉토리 내에 있는 상태로 올라갔을까요....?

2022-06-09 08:28 UTC, chae-yh approved these changes
민성님 안녕하세요! 피드백 잘 반영해주셨습니다 👍 
질문 주신 내용은 코멘트 드렸는데, 혹시 추가로 확인하실 내용 있으시면 dm 등 언제든지 부탁드립니다!

이제 마지막 step 이네요! 파이팅 입니다 : )

2022-06-09 08:28 UTC, chae-yh commented on build.gradle
> +	implementation 'org.flywaydb:flyway-core'
flyway도 적용해보셨네요 좋습니다 👍

2022-06-09 08:28 UTC, merged