step1. 0단계, 1단계 과제 수행
next-step/infra-subway-deploy pull request #551
Opened 2022-06-09 14:00 UTC by nocomet

안녕하세요 그럴듯한 서비스 만들기 step1 pr 드립니다~
네트워크 인프라가 잘 갖춰진 회사에서 근무하다보니 인프라 부분이 평소 매우 취약했는데,, 이번 기회에 많은 부분을 배울 수 있어서 좋은 것 같습니다!
덕분에 삽질도 많이 한 것 같습니다 ^^;;;
회사 업무로 진행이 조금 더딘 것 같지만 열심히 해보겠습니다 감사합니다

2022-06-10 14:23 UTC, oper912 requested changes
안녕하세요 혜성님 :)
그럴듯한 서비스 만들기 미션 함께 하게된 권순호 입니다 🙂

1단계 리소스 생성 해주신 것 확인하였습니다 👍
요구사항을 충족하지 못하는 부분이 있는 것 같아서 코멘트 남겼는데 
슬랙 설정과 함께 다시 확인 부탁드려요
확인하시구 리뷰 재요청 해주세요 🙏

2022-06-10 14:23 UTC, oper912 commented on README.md
> +- URL : http://nocomet-subway.kro.kr/
현재 도메인으로 요청시 웹서버IP 로 리다이렉트 되고 있는데 DNS A 레코드에 제대로 등록된건지 포워딩 설정이 된건지 확인해봐야 될 것 같습니다

2022-06-10 14:23 UTC, oper912 commented on README.md
> +- nocomet-key-pair.pem
관리망에서 외부망, 내부망 접근이 안되는데 다시 확인부탁드립니다

2022-06-11 01:21 UTC, nocomet commented on README.md
> +- nocomet-key-pair.pem
베스천 서버에 연결된 라우팅 테이블 nocomet-admin-rt`에 igw 가 연결되어 있지 않으면 외부 ip에서 ssh으로 접속이 안되는 것 같던데요. 여기에도 igw를 삭제해야하는걸까요?

2022-06-11 01:25 UTC, nocomet commented on README.md
> +- nocomet-key-pair.pem
`베스천 서버` → `웹 서버(외부망-192-168-91-33)`
```
[BASTION][01:24:14][ubuntu@ip-192-168-91-176 ~]
$ ssh 192.168.91.33
Welcome to Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-1071-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Sat Jun 11 01:24:26 UTC 2022

  System load:  0.0               Processes:           103
  Usage of /:   34.6% of 7.69GB   Users logged in:     0
  Memory usage: 20%               IP address for ens5: 192.168.91.33
  Swap usage:   0%

 * Ubuntu Pro delivers the most comprehensive open source security and
   compliance features.

   https://ubuntu.com/aws/pro

15 updates can be applied immediately.
To see these additional updates run: apt list --upgradable

New release '20.04.4 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


*** System restart required ***
Last login: Sat Jun 11 01:23:55 2022 from 192.168.91.176
```

`베스천 서버` → `db 서버(내부망-192.168.91.144)`
```
[BASTION][01:25:25][ubuntu@ip-192-168-91-176 ~]
$ ssh 192.168.91.144
Welcome to Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-1071-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Sat Jun 11 01:25:30 UTC 2022

  System load:  0.0               Processes:           101
  Usage of /:   20.2% of 7.69GB   Users logged in:     0
  Memory usage: 6%                IP address for ens5: 192.168.91.144
  Swap usage:   0%

 * Ubuntu Pro delivers the most comprehensive open source security and
   compliance features.

   https://ubuntu.com/aws/pro

70 updates can be applied immediately.
57 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable

New release '20.04.4 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


Last login: Sat Jun 11 01:24:04 2022 from 192.168.91.176
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

ubuntu@ip-192-168-91-144:~$
```

2022-06-11 01:26 UTC, nocomet commented on README.md
> +- nocomet-key-pair.pem
@oper912 저는 접속이 잘 되는 것 같은데,, 혹시 제가 잘못 설정한 부분이 있을까요?

2022-06-11 01:29 UTC, nocomet commented on README.md
> +- URL : http://nocomet-subway.kro.kr/
앗 넵 제가 웹 포워팅 형식으로 연결하였습니다.

DNS IP연결(A) 방식으로 변경하였습니다.

2022-06-12 04:18 UTC, oper912 commented on README.md
> +- URL : http://nocomet-subway.kro.kr/
현재는 도메인으로는 접속이 안되네요 ㅠ 다음 단계 진행하면서 확인 부탁드립니다

2022-06-12 04:27 UTC, oper912 commented on README.md
> +- URL : http://nocomet-subway.kro.kr/
아하 http://nocomet-subway.kro.kr:8080  포트포워딩딩을 하지 않아서 포트 생략을 하면 안되는거였네요
포트포워딩을 통해 8080 포트도 제거해볼 수 있을 것 같습니다 참고만 부탁드려요

2022-06-12 04:28 UTC, oper912 commented on README.md
> +- nocomet-key-pair.pem
제가 확인을 잘못했나봐요🙏 관리망에서 외부망, 내부망 접근가능한 것 확인했습니다!

현재는 내부망을 위한 라우팅 테이블에도 인터넷게이트웨이가 연결되어있는데 이렇게되면 내부망 외부망 분리의 목적이 사라지는거 같아서  [NAT Gateway](https://galid1.tistory.com/367)를 활용해보시면 좋을 것 같습니다
이 부분은 일단 참고만 부탁드립니다 

베스천서버는 인터넷게이트웨이 유지해도 될 것 같습니다!

2022-06-12 04:30 UTC, oper912 approved these changes
피드백 반영 잘해주셨네요 👍
질문에 대한 답변 코멘트에 남겨놓았으니 확인 부탁드립니다
다음 단계 진행해주세요~ 💪

2022-06-12 04:30 UTC, merged