Step2 - 서비스 배포하기
next-step/infra-subway-deploy pull request #553
Opened 2022-06-09 15:02 UTC by songsimo

안녕하세요, 2번째 과제 서비스 배포하기 제출입니다. 😄

step2 브랜치가 이미 존재한다고 push가 안 돼서 브랜치명을 살짝 바꾸었습니다.

이번 PR도 잘 부탁드립니다. 리뷰어님 ^^

+ 과제 진행후 인스턴스를 중지시켰는데 연습하다가 (권한 문제로) 못 지운 인스턴스 2개가 있어

아무래도 리뷰어님이 헷갈렸을거 같네요. 안 쓰는 인스턴스는 `-romove`를 명에 붙여두었습니다.

죄송합니다 🙇 🙇

2022-06-10 15:28 UTC, shared-moon commented
음 .. 이상하네요! 인스턴스가 이날 20:59분에 올라간걸로 봐서 제가 잘못본건 아닌거같은데 ㅎㅎ 전부 다 내려가있었거든요!

2022-06-10 15:58 UTC, shared-moon requested changes
안녕하세요 철현님!
코멘트 남겨 두었는데 확인 후 리뷰 요청 다시 부탁드려요!
화이팅하세요! 🔥

2022-06-10 15:58 UTC, shared-moon commented on README.md
> +- URL : https://songsimo.kro.kr
접속이 안되는데 확인 부탁드려요!

2022-06-10 15:58 UTC, shared-moon commented on README.md
> +  - [x] Reverse Proxy에 TLS 설정
TLS 설정 되고나면 public에는 80번 포트 안열어도 되지 않을까요 ?

2022-06-11 09:20 UTC, songsimo commented on README.md
> +- URL : https://songsimo.kro.kr
네! 인스턴스만 켜놓고  자바를 백그라운드로 실행 안 해놓았네요 🤨🙄

다시 확인했습니다 🙇

2022-06-11 09:21 UTC, songsimo commented on README.md
> +  - [x] Reverse Proxy에 TLS 설정
넵! 80포트 닫아 놓겠습니다 = )

2022-06-11 09:25 UTC, songsimo commented
aws 설정 부분들이라 추가적인 커밋은 안하고 리뷰 요청 보냈는데 괜찮을까요?

2022-06-11 10:20 UTC, shared-moon approved these changes
철현님 안녕하세요!
피드백 반영 해 주신 것 확인 했습니다 :)

이번 미션은 머지 하도록 하겠습니다!
고생 많으셨어요 :)

2022-06-11 10:20 UTC, merged