3단계 배포 스크립트 작성하기
next-step/infra-subway-deploy pull request #567
Opened 2022-06-11 16:25 UTC by minzzang

안녕하세요 리뷰어님!

3단계 배포 스크립트 미션 리뷰 요청드립니다.

감사합니다!

2022-06-12 14:55 UTC, jaeyeonling requested changes
배포 스크립트를 잘 작성해주셨네요 👍 
소소한 코멘트 남겨두었으니 확인 부탁드릴게요 :)

2022-06-12 14:55 UTC, jaeyeonling commented on README.md
> +function killProcess() {
사실 pid는 해당 메서드에서만 사용하기 때문에 전역으로 관리하지 않아도 될 것 같은데 어떻게 생각하시나요?

2022-06-15 10:54 UTC, minzzang commented on README.md
> +function killProcess() {
넵 전역으로 관리할 필요가 없는 것 같습니다! 수정하겠습니다.

2022-06-16 05:55 UTC, jaeyeonling approved these changes
코멘트를 잘 반영해주셨습니다 👍 
미션 진행하시느라 고생 많으셨어요~ 
마지막까지 힘내주시고 좋은 소식으로 다시 뵙겠습니다 😄

2022-06-16 05:55 UTC, merged