Step2 - 서비스 배포하기
next-step/infra-subway-deploy pull request #568
Opened 2022-06-11 16:34 UTC by jaesungahn91

많은 피드백 부탁드립니다! 감사합니다!
잘하고있는지 모르겠습니다 ㅠㅠ

2022-06-12 03:50 UTC, seok-2-o requested changes
두번째 미션 잘 진행해주셨네요.
요구사항을 만족하지 않는 부분이 있어 코멘트로 남겨드렸습니다.
확인 후 개선해주세요.

2022-06-12 03:50 UTC, seok-2-o commented on README.md
> +#### 운영 환경 구성하기
TLS 를 적용한 주소로 문서도 변경해주는게 좋을 것 같아요.

2022-06-12 03:50 UTC, seok-2-o commented on src/main/resources/application-local.properties
> +spring.datasource.driver-class-name=org.h2.Driver
설정 파일 나누기
**JUnit** : h2, **Local** : docker(mysql), **Prod** : 운영 DB를 사용하도록 설정

요구사항을 보면 3개의 설정파일을 생성하도록 안내하고 있어요.

2022-06-12 07:49 UTC, jaesungahn91 commented on README.md
> +#### 운영 환경 구성하기
죄송합니다. 반영하고 제대로 확인을 못했습니다ㅠㅜ

2022-06-13 02:53 UTC, seok-2-o approved these changes
피드백 반영 잘해주셨네요.
이어서 다음 미션 진행해주세요.

2022-06-13 02:53 UTC, merged