Step3 - 배포 스크립트 작성하기
next-step/infra-subway-deploy pull request #572
Opened 2022-06-12 05:14 UTC by kmmin78

안녕하세요, 영훈님! 🙇‍♂️

4주차 그럴듯한 서비스 만들기 미션의 3단계 - 배포 스크립트 작성하기 PR 드립니다!

shell script 하면 할 수록 재밌었습니다! 능숙해지면 더 효과적으로 작성할 수 있을 것 같네요 😁

마지막 리뷰도 잘부탁드립니다. 🙂

2022-06-12 15:23 UTC, chae-yh requested changes
민성님 안녕하세요! 이제 마지막 step 이네요! 고생 많으셨습니다!
전체적으로 쉘 스크립트 잘 작성해주셨습니다. 저도 배우게 되네요 ㅎㅎ
다만 바로 merge 하기에는 조금 고민해보시면 좋을만한 내용이 있어 코멘트 드리니 확인 부탁드립니다!

감사합니다 : )

2022-06-13 11:22 UTC, kmmin78 commented on deploy.sh
> +#  submodule;
서브모듈을 가져오는 함수인데요!
쉘 작성 당시에는 서브모듈을 매번 업데이트 해야하는 로직이 필요하다고 생각했었는데,
맨 처음 pull 받았을 때에만 진행해도 될 것 같다고 판단해서 주석처리했습니다!
해당 내용은 삭제 진행하겠습니다!

2022-06-13 11:44 UTC, kmmin78 commented on deploy.sh
> +    kill -2 "${PID}"
kill 옵션이 SIGINT (-2)일 경우에 어플리케이션이 graceful shutdown 및 shutdown hook 호출을 할 수 있습니다.
graceful shutdown이란 어플리케이션이 종료될 때, 정상적으로 리소스를 해제하고, 요청을 처리하고, 프로세스를 종료하는 것을 의미합니다.
만약 kill -9  (SIGKILL) 옵션으로 프로세스를 종료하게 되면, 자바 어플리케이션에서는 shutdown hook을 실행하지 못하고 강제종료하게 되는데, 이는 기존에 처리하고 있던 작업이 있으면 (e.g. database crud) 정상적으로 롤백하거나 처리를 마무리하지 못하고 종료하게 되어 오류를 유발할 수 있습니다.
-15 (SIGTERM) 역시 shutdown hook이 호출되지만 -2 (SIGINT) 옵션과 달리 gracefully exit을 하지 않는다고 합니다.

따라서 SIGINT (-2) 옵션이 가장 안전한 방법이라고 하네요 ㅎㅎ; 
덕분에 새로운 걸 알게되었습니다.
감사합니다! 😊

[Capture SIGINT in Java](https://stackoverflow.com/questions/2541475/capture-sigint-in-java)
[JVM의 종료와 Graceful Shutdown](https://effectivesquid.tistory.com/entry/JVM%EC%9D%98-%EC%A2%85%EB%A3%8C%EC%99%80-Graceful-Shutdown)

2022-06-13 12:13 UTC, kmmin78 commented on deploy.sh
> +#!/bin/bash
크론 적용 및 권한 변경 완료했습니다!

2022-06-13 23:55 UTC, chae-yh approved these changes
민성님 안녕하세요! 피드백 잘 반영해주셨습니다 💯 
리눅스 명령어 관련해서 저도 도리어 많이 배우게 되었습니다 감사합니다 : )

그리고, 이것으로 그럴듯한 서비스 만들기도 미션 종료되었습니다! 고생많으셨습니다 ㅎㅎ
나름대로는 열심히 리뷰드리려고 노력했는데, 민성님께 조금이나마 도움이 되셨으면 좋겠습니다!
이번 미션 종료로 거의 반환점을 돈 것이라 생각이 듭니다. 앞으로도 지금처럼 열정적인 모습으로 미션 끝까지 완수하시길 빌겠습니다!

다시 한번 고생 많으셨습니다! 감사합니다!

2022-06-13 23:55 UTC, merged