2단계 - 서비스 배포하기
next-step/infra-subway-deploy pull request #643
Opened 2022-06-21 15:40 UTC by mukeunzi

석홍님 안녕하세요!! 😃

이번 미션 하면서 많이 헤맸는데 마무리하고 PR을 보낼 수 있어서 너무 기쁩니다..ㅠㅠㅠ
여러 질문에 친절히 도움 주셔서 너무 감사합니다!!

먼저, 아까 허들하면서 질문주셨던 `DatabaseCleanup.java`에서 `@ActiveProfiles("test")` 가 test로 설정되었음에도 불구하고 실행 시 local을 참조했던 이유는, profiles를 참조하는 우선순위 때문이라고 이해했습니다! 
그 이유는 `application.properties` 에서 active를 local로 설정했기 때문인 것으로 확인했습니다. 

이번 미션 관련해서는,
이전 Step1 미션에서 NAT Gateway를 생성해두긴 했는데 private ec2의 라우팅 테이블에 연결을 안 해둬서 설정 후 진행했습니다! 

확인 부탁드리겠습니다!! Step3 에서 다시 뵙겠습니다! 🏃

2022-06-22 00:19 UTC, seokhongkim requested changes
은지님, 2단계 미션 잘 진행해주셨습니다!
미션 진행하시며 어려운 부분이 많았을텐데 그래도 하나씩 해결 방법을 잘 찾아주셨네요. 👍 

코멘트 조금 남겼는데 확인 부탁드립니다. 🙏

2022-06-22 00:19 UTC, seokhongkim commented on README.md
> +- URL : https://mukeunzi-ec2-service.o-r.kr
TLS 설정 및 http 로 접속 시 https 로 리다이렉트 되는 것 확인했습니다. 👍

2022-06-22 00:19 UTC, seokhongkim commented on src/main/resources/application-local.properties
> +spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
환경별로 설정 분리 잘 해주셨습니다!

2022-06-22 00:19 UTC, seokhongkim commented on src/main/resources/application-local.properties
> +spring.jpa.properties.hibernate.format_sql=true
파일 마지막에 newline 이 누락되다고 경고를 띄워주네요.
파일 마지막 newline 은 왜 필요한걸까요?

2022-06-22 00:19 UTC, seokhongkim commented on src/main/resources/application-test.properties
> +spring.datasource.url=jdbc:h2:mem:test
test 설정 잘 추가해주셨습니다.

> 먼저, 아까 허들하면서 질문주셨던 DatabaseCleanup.java에서 `@ActiveProfiles("test")` 가 test로 설정되었음에도 불구하고 실행 시 local을 참조했던 이유는, profiles를 참조하는 우선순위 때문이라고 이해했습니다!
그 이유는 application.properties 에서 active를 local로 설정했기 때문인 것으로 확인했습니다.

아마 현재 테스트를 실행하시면 프로필이 `local` 로 실행되면서 테스트가 깨질 것 같아요.
테스트를 실행할 때 실행되는 클래스는 무엇일까요? 그 실행되는 클래스를 찾아서 `@ActiveProfiles("test")` 를 설정한 후 테스트 실행해보시면 좋을 것 같습니다. :)

2022-06-22 00:19 UTC, seokhongkim commented on README.md
> +- [x] 웹 애플리케이션 앞단에 Reverse Proxy 구성하기
nginx 설정 해주신 것과 운영 DB에 연결해서 서비스 동작하는 것 확인했습니다. 💯

2022-06-23 01:22 UTC, mukeunzi commented on src/main/resources/application-test.properties
> +spring.datasource.url=jdbc:h2:mem:test
넵! 반영하겠습니다 :)

2022-06-23 01:34 UTC, mukeunzi commented on src/main/resources/application-local.properties
> +spring.jpa.properties.hibernate.format_sql=true
New line, File에 대한 POSIX 표준 때문입니다! 
사용중인 IDE에 포맷팅 설정하여 자동 개행할 수 있도록 하겠습니다 ㅎㅎ

2022-06-23 09:34 UTC, seokhongkim approved these changes
은지님, 2단계 미션 피드백 잘 반영해주셨습니다. 👍 
이번 단계 PR은 이만 머지하도록 하겠습니다.

3단계 미션에서 뵙겠습니다. 😀

2022-06-23 09:34 UTC, merged