1주차 1단계 - 망 구성하기
next-step/infra-subway-deploy pull request #657
Opened 2022-06-23 13:25 UTC by ejolie

안녕하세요. 1주차 1단계 과제 제출합니다.
AWS랑 네트워크 구성이 익숙하지 않아 삽질하며 많이 배웠네요. 😅 
감사합니다.

2022-06-23 15:09 UTC, brainbackdoor requested changes
서버가 정상적으로 안 떠 있는데, 확인 부탁드려요~
좋은 밤 보내세요~

2022-06-24 06:29 UTC, ejolie commented on README.md
> +- URL : http://nextstep-ejolie.n-e.kr/
`nohup`으로 실행하지 않아서 그런 것 같네요. 다시 확인 부탁드립니다! 🙏🏼

2022-06-24 06:35 UTC, ejolie commented on README.md
> +- URL : http://nextstep-ejolie.n-e.kr/
오잉 접속이 정상적으로 안되네요. 다시 확인하고 리뷰 요청드리겠습니다.!

2022-06-24 06:59 UTC, ejolie commented on README.md
> +- URL : http://nextstep-ejolie.n-e.kr/
잠시 2단계 과제를 진행하면서 뭔가 꼬인 것 같네요. 😓 다시 확인 부탁드립니다. 🙏🏼

2022-06-25 04:21 UTC, brainbackdoor approved these changes
1단계 미션 진행하느라 고생하셨어요~ 
이번 단계는 여기서 머지할게요~ 주말 잘 보내세요! 👋🏻

2022-06-25 04:21 UTC, merged