[1주차 step2] - 배포하기
next-step/infra-subway-deploy pull request #673
Opened 2022-06-25 08:02 UTC by jihye-woo

안녕하세요!!! 즐거운 토요일입니다아🙌
이제야 2단계 PR 리뷰 요청드려요ㅠ 감사합니다🙏

2022-06-25 13:07 UTC, brainbackdoor requested changes
2단계 미션 잘 진행하셨네요~ 👍🏻 
몇가지 확인할 부분이 있어서 피드백 남겼어요~ 확인 바래요~

2022-06-25 13:07 UTC, brainbackdoor commented on README.md
> +- URL : https://jihye-woo.n-e.kr/
<img width="945" alt="스크린샷 2022-06-25 오후 10 00 46" src="https://user-images.githubusercontent.com/29951288/175774549-edc12700-23f0-4835-8d37-e42f44201b8f.png">

앗, 502 에러가 납니다. 다른 작업 진행중이시려나요..
로그만 봤을 떄는 nohup으로 실행하지 않아, 터미널 세션이 끊기면서 서버 프로세스가 죽은 것으로 보이네요;

2022-06-25 13:07 UTC, brainbackdoor commented on src/main/resources/application-local.yml
> +      ddl-auto: validate
로컬에선 validate 설정을 하지 않는 편이에요. 개발 편의성을 위해 (저의 경우 flyway migration 쿼리를 jpa ddl 쿼리를 활용하는 편이거든요) create-drop 혹은 create 로 두는 편이에요

2022-06-25 13:07 UTC, brainbackdoor commented on src/main/resources/application-prod.yml
> +      ddl-auto: validate
public 서버의 db container는 내려도 되지 않을까요?
불필요한 리소스를 사용하고 있을듯해서요

2022-07-02 11:22 UTC, jihye-woo commented on src/main/resources/application-prod.yml
> +      ddl-auto: validate
public 서버의 db container 내리는걸 깜빡했네요! db container는 internal에만 띄워놓았습니다

2022-07-02 11:23 UTC, jihye-woo commented on README.md
> +- URL : https://jihye-woo.n-e.kr/
https://jihye-woo.n-e.kr/
현재는 정상 접속됩니다!

2022-07-02 11:24 UTC, jihye-woo commented on src/main/resources/application-local.yml
> +      ddl-auto: validate
앗 그렇군요ㅠㅠ create으로 변경해두었습니다!

2022-07-02 13:07 UTC, brainbackdoor approved these changes
2단계 미션 진행하느라 고생하셨어요! 👍🏻 
이번 단계는 여기서 머지할게요~ 다음 단계도 파이팅입니다~ 💪🏻
주말 밤 잘 보내시고, 내일 뵈어요~ 👋🏻

2022-07-02 13:07 UTC, brainbackdoor commented on README.md
> +- URL : https://jihye-woo.n-e.kr/
이제 더이상 8080 open 정책은 필요하지 않아요. 필요한 대상에게만 오픈하도록 정책 반영 바래요~

2022-07-02 13:07 UTC, merged