Step2 : 배포하기
next-step/infra-subway-deploy pull request #774
Opened 2022-08-18 15:41 UTC by becky-bigc

- [x] 웹 애플리케이션 앞단에 Reverse Proxy 구성하기
    - [x] 외부망에 Nginx로 Reverse Proxy를 구성
        - [x] Reverse Proxy에 TLS 설정
        - [x] 운영 데이터베이스 구성하기
- [x] 개발 환경 구성하기
    - [x] 설정 파일 나누기
        - [x] JUnit : h2, Local : docker(mysql), Prod : 운영 DB를 사용하도록 설정

2022-08-18 17:14 UTC, brainbackdoor requested changes
2단계 미션 진행하느라 고생하셨어요~ 👍🏻 
확인할 부분이 있어 피드백 남겼어요~
좋은 밤 보내세요~

2022-08-18 17:14 UTC, brainbackdoor commented on README.md
> +- URL : https://www.becky-infra.r-e.kr/
<img width="632" alt="스크린샷 2022-08-19 오전 2 10 40" src="https://user-images.githubusercontent.com/29951288/185454742-ccc49bf3-1d55-4ace-996c-429290941b8a.png">
<img width="451" alt="스크린샷 2022-08-19 오전 2 11 27" src="https://user-images.githubusercontent.com/29951288/185454761-b821a9b2-3352-4aa3-98fb-8874166890b8.png">

`becky-infra.r-e.kr`에 대해 TLS 인증받고 `www.becky-infra.r-e.kr` DNS 주소를 등록하셨네요~

2022-08-19 14:05 UTC, becky-bigc commented on README.md
> +- URL : https://www.becky-infra.r-e.kr/
피드백 감사합니다. 수정했습니다!

2022-08-19 16:38 UTC, brainbackdoor approved these changes
피드백 확인했어요~ 2단계 미션 진행하느라 고생하셨어요~
주말 잘 보내세요~

2022-08-19 16:38 UTC, merged