[Step1] 망 구성하기
next-step/infra-subway-deploy pull request #789
Opened 2022-08-20 12:06 UTC by Kodo92

늦어서 죄송합니다 ㅜㅜ

2022-08-20 15:01 UTC, Kodo92 commented
step 2도 이어서 진행하였습니다.
TLS 가이드대로 진행하였지만 첨부한 이미지와 같은 문제가 발생하고 있습니다.
![image](https://user-images.githubusercontent.com/18136160/185752981-716ed111-c779-4eff-aa45-4811b6f152db.png)

2022-08-21 05:57 UTC, brainbackdoor requested changes
2단계 미션까지 진행하시느라 고생 많으셨어요~ 👍🏻 
몇가지 확인할 부분들이 있어 피드백 남겼어요~ 
확인해보시고 궁금한 점은 메시지 주세요~
주일 잘 보내세요~

2022-08-21 05:57 UTC, brainbackdoor commented on README.md
> +- URL : https://www.kodo92.kro.kr
<img width="665" alt="스크린샷 2022-08-21 오후 2 50 32" src="https://user-images.githubusercontent.com/29951288/185777581-f4ff79ed-b029-4eec-9b4d-5f2688b516f4.png">

강의때 말씀드렸듯, tls 인증서는 kodo92.kro.kr로 인증 받고, dns 설정은 www.kodo92.kro.kr 로 설정하여 발생한 이슈입니다.
확인 바래요~

2022-08-21 05:57 UTC, brainbackdoor commented on src/main/resources/application-prod.properties
> +spring.jpa.hibernate.ddl-auto=validate
운영환경에도 prod 설정으로 배포하는 것도 요구사항입니다.

2022-08-21 05:57 UTC, brainbackdoor commented on src/main/resources/application-test.properties
> +account.password = test
예제로 드렸던 설정은 제거하셔도 됩니다.
application-test.properties에는 junit 과 관련된 설정들을 다루면 됩니다.

2022-08-21 05:57 UTC, brainbackdoor commented on src/main/resources/application-local.properties
> +spring.jpa.hibernate.ddl-auto=validate
local에서는 개발 편의성을 위해 validate보다는 create 혹은 create-drop을 주로 사용하는 편입니다.

2022-09-15 21:12 UTC, closed without merging