[1단계] 망구성하기
next-step/infra-subway-deploy pull request #832
Opened 2022-09-22 01:27 UTC by dldydtjs2965

- [x] 망 구성 
- [x] 베스천 서버 환경 설정
- [x] 어플리케이션 배포후 DNS 연동
전부 완료했습니다. 리뷰 부탁드립니다~!

2022-09-22 08:30 UTC, brainbackdoor requested changes
1단계 미션 진행하느라 고생하셨어요~ 👍🏻 
몇가지 확인할 부분이 있어 피드백 남겼어요~
좋은 하루 보내세요~

2022-09-22 08:30 UTC, brainbackdoor commented on README.md
> +- 대역 : 192.168.97.0/32
요구사항은 외부망 2개, 내부망 1개, 관리망 1개예요
그리고 bastion 서버는 관리망에 위치하는 것이구요

현재는 외부망 2개, 내부망 2개로 구성되어 있고, 내부망의 경우 bastion 서버 eni에 대해 학습을 시켜두었던데요.
NAT gateway를 구성해서 내부망 -> 외부망 연결이 가능하도록 구성하시면 되어요

2022-09-22 08:30 UTC, brainbackdoor commented on README.md
> +- 대역 : 192.168.97.0/32
80 요청에 대해 8080으로 포트포워딩 정책을 추가하셨는데요.
2단계에서 443, 80 요청에 대해 8080으로 전달하도록 reverse proxy 구성을 할거라 정책을 뺴두셔도 됩니다 😬

2022-09-22 13:43 UTC, dldydtjs2965 commented on README.md
> +- 대역 : 192.168.97.0/32
리뷰 감사합니다! 자세한 피드백 감사드립니다 :) 관리망을 구축하고 EC2에서 eni를 이전할 수 없어서 
EC2-dldydtjs2965-bastion-2로 다시 생성하고 말씀하신대로 public서버에 설정된 iptable을 뺐습니다~!

2022-09-22 14:28 UTC, brainbackdoor approved these changes
피드백 반영 잘해주셨네요~ 👍🏻 
한가지 추가로 피드백해두었으니 다음 단계 진행할 때 반영 바래요~
좋은 밤 보내세요~

2022-09-22 14:28 UTC, brainbackdoor commented on README.md
> +- 대역 : 192.168.97.0/32
내부망 서버에서 3306 포트에 대해 public 서버 공인 IP (43.200.158.163/32)에 대해 허용 정책을 추가해두었는데요
내부망 구조상 public -> internal 접근이 안될거에요.
그 이유는 내부망은 인터넷 망 -> 내부망 접근이 현재 안되는데 공인 IP에 대해 허용했다는 의미는 저 공인 IP를 source IP로 두고 인터넷망으로 나갔다가 다시 들어올 때 허용하겠다는 의미거든요
private IP 에 대해 허용해주셔야 해요

2022-09-22 14:28 UTC, merged

2022-09-23 05:09 UTC, dldydtjs2965 commented on README.md
> +- 대역 : 192.168.97.0/32
제가 세세한 부분에서 놓칠 수 있는 것 까지 캐치해주시고 자세한 리뷰주셔서 감사합니다 ㅠㅠ
탄력적 IP를 사용하면 인터넷 망을 통해 접근한다는 것을 머리로는 이해하고 정작 다르게 행동하고 있었네요 ㅎㅎ 
덕분에 문제가 생길 수 있는 것을 방지할 수 있었습니다. 감사합니다~