[Step1] 서비스 구성하기
next-step/infra-subway-deploy pull request #871
Opened 2022-11-14 12:34 UTC by ychxexn

안녕하세요.

Step1 서비스 구성하기에 대한 PR 요청드립니다.
AWS를 다루는 게 처음이라 힌트를 보면서도 무척 헤맸어요.
아직 강의를 듣기 전이라 그런지 해놓고도 이게 맞는지 의문이 드네요.

그럼 잘 부탁드립니다!

2022-11-15 12:34 UTC, chae-yh requested changes
채은님 안녕하세요. 그럴듯한 서비스만들기 리뷰를 맡은 채영훈입니다. 반갑습니다 ㅎㅎ
AWS를 처음사용해보셨다고 하셨는데, 전체적으로 환경 구성 잘 해주신 것 같습니다 👍 다만 확인이 필요한 부분이 조금 보여서 코멘트 드리니 확인 부탁드립니다.

감사합니다 : )

2022-11-15 12:34 UTC, chae-yh commented on README.md
> +- 대역 : 172.31.32.0/20
AWS를 처음 사용해주셨다고 말씀해주셨는데, 환경 구성 잘해주신 것 같아요. 다만, 확인이 필요한 내용이 있어 아래와 같이 내용 남깁니다.

**서비스 구성하기 체크 리스트**

- VPC구성 : SERVICE-APPLY 로 구성해주신 것 같은데, 대역이 너무 큽니다.(172.31.0.0/16) 그리고, 다른분들이 만든 리소스와 구분하기 쉽게, 아이디를 넣어서 만들어주셔도 좋을 것 같아요. 태그도 구분이 안되어서, 아이디를 넣어서 만들어주세요..! 
`모든 리소스는 태그를 작성합니다. 이 때 자신의 계정을 Prefix로 붙입니다. (예: brainbackdoor-public)`
 ex) ychxexn-vpc
- 서브넷 구성 : APPLY-a / APPLY-b / APPLY-c 로 구성해주신 것 같은데, 이것도 이름 수정이 필요하고, 범위가 너무 크네요. 추가로 public 2개 / private 1개 / batstion 1개로 구성해주시면 좋을 것 같습니다 : )
- 라우팅 테이블 : RT-APPLY로 만들어주셨는데, 이름 고치면 좋을 것 같아요...!
- 인터넷 게이트웨이 : IGW-APPLY로 만들어주셨는데, 이 부분도 이름 고쳐주세요...!
- 인스턴스 구동 : 동일한 APPLY-b에 구성되어 있는데, 서브넷 별로 인스턴스를 띄워주세요..!
- 보안그룹 : 보안 그룹(launch-wizard-5, launch-wizard-6)도 이름 변경이 필요해보이고, public, private, bastion별로 따로 만들어주세요..!
- 호스팅 한 url로 접근: 이 부분은 잘 된 것 같아요...!
- 별칭 설정 : bastion에서 각 서버로 쉽게 접근할 수 있도록 별칭 설정 부탁드립니다..!
- 환경변수 적용(세션 타임 아웃, history에 시간 추가) : 잘 된 것 같습니다..!
- 쉘 프롬프트 변경 : BASTION / SERVICE 잘 변경해주셨습니다 👍 
- logger 사용 : 원격지에 로그가 쌓이도록 설정되지는 않은 것 같아요...! 가능하면 bastion에 남겨보면 좋을 것 같습니다 ㅎㅎ
- 어플리케이션 구동 : 백그라운드로 실행이 안된 것 같아요..! 
- 어플리케이션 로그 : 어플리케이션 로그가 따로 남지 않는 것 같아요. 서버에 쌓이도록 추가 설정부탁드립니다..!

전체적으로 리소스에서 채은님이 만드신 리소스를 찾기가 어렵습니다. 아이디를 prefix로 해서 구별하기 쉽게 많들어 주시면 좋을 것 같아요...!

2022-11-18 15:18 UTC, ychxexn commented on README.md
> +- 대역 : 172.31.32.0/20
알려주신 부분 모두 수정해서 EC2 인스턴스 새로 만들고, 환경 설정도 완료했습니다 👍
제가 많이 귀찮게 했는데도 친절하게 알려주셔서 감사드려요!
다시 한 번 확인 부탁드립니다 ~!

2022-11-20 00:14 UTC, chae-yh approved these changes
채은님 안녕하세요! 피드백 드린 양이 조금 많았는데, 전체적으로 잘 반영해주셨습니다 👍 확인이 필요해보이는 부분이 조금 남아 있기는 한데, 크리티컬한 부분은 아니라서 여기서 merge하겠습니다..! 다음 step 진행하면서 확인 부탁드립니다.

감사합니다 : )

2022-11-20 00:14 UTC, chae-yh commented on README.md
> +- URL : http://subway.wtcpro-ychxexn.o-r.kr/
**서비스 구성하기 체크 리스트**

- VPC구성 [O]
- 서브넷 구성 [O]
- 라우팅 테이블 [O]
- 인터넷 게이트웨이 [O]
- 인스턴스 구동 [O]
- 보안그룹 -> public 에 걸려있는 보안그룹에 ssh접근이 모든 ip에 대해서 열려있네요..! 22로 접근은 batstion에 대해서만 열려있는게 좋을 것 같아요..!
- 호스팅 한 url로 접근 [O]
- 별칭 설정 [O]
- 환경변수 적용(세션 타임 아웃, history에 시간 추가) [O]
- 쉘 프롬프트 변경 [O]
- logger 사용 [O]
- 어플리케이션 구동 [O]
- 어플리케이션 로그 -> 이 부분은 제가 못찾는 것 같아요..! 해당 어플리케이션 쌓이는 디렉토리 부탁드립니다..!

2022-11-20 00:14 UTC, merged

2022-11-20 02:17 UTC, ychxexn commented on README.md
> +- URL : http://subway.wtcpro-ychxexn.o-r.kr/
public 보안그룹 bastion에만 열려있게 수정했습니다!
로그 위치는 /home/ubuntu/nextstep/infra-subway-deploy/subway.log 입니다 🙂