1단계 - 서비스 구성하기
next-step/infra-subway-deploy pull request #887
Opened 2022-11-19 15:20 UTC by iamsojung

안녕하세요 !!

4주차 1단계 PR 요청드립니다.
쉬어가는주인줄 알고 시작했다가 한참 헤맸습니다..🥲

그럼 잘 부탁드립니다!

2022-11-20 05:26 UTC, heowc requested changes
안녕하세요. 이번 미션에 리뷰어를 맡게된 허원철입니다. 🙇 

vpc나 subnet 설정을 잘해주신 것 같아요~ 다만 접근이 안되어 정확한 확인이 안되고 있는 것 같습니다.

궁금하신 점이나 이야기 나누고 싶은 부분이 있다면 깃헙 코멘트, 슬랙 DM 편하게 남겨주세요!

2022-11-20 05:26 UTC, heowc commented on README.md
> +* key-iamsojung.pem
pem 가 검색이 안되어 찾아보니 iamsojung.pem으로 되어 있는 것 같습니다. 다만, 해당 pem으로 베스천 서버 접근이 안되는데 확인 부탁드려요 🙇 
- 인스턴스마다 다른 pem 키를 갖고 있는 것 같습니다 🤔

2022-11-20 05:26 UTC, heowc commented on README.md
> +- URL : iamsojung-webservice.kro.kr (http://3.39.154.48:8080/)
해당 url과 ip로는 접근 안되는 것 같아요~
- pem가 안맞아서 stop 되어 있던 인스턴스를 제가 다시 올리긴 했는데 리뷰 받을 인스턴스는 실행된 상태로 유지시켜주심 좋을 것 같습니다 🙇

2022-11-20 05:26 UTC, heowc commented on README.md
> +* iamsojung-public-subnet01 (192.168.16.0/26)
public 관련 security group에 ICMP 관련 프로토콜이 전체 오픈되어 있는 것 같아요 🤔

2022-11-21 11:51 UTC, iamsojung commented on README.md
> +* key-iamsojung.pem
앗 key-iamsojung으로 다시 업로드 했습니다 !!

2022-11-21 11:52 UTC, iamsojung commented on README.md
> +- URL : iamsojung-webservice.kro.kr (http://3.39.154.48:8080/)
t4g.medium 말고 t3.medium 사용하라고 해서,, t4g.medium 2개는 일부러 다 내려두었습니다.!

2022-11-21 12:15 UTC, iamsojung commented on README.md
> +* iamsojung-public-subnet01 (192.168.16.0/26)
수정했습니다!

2022-11-21 12:18 UTC, iamsojung commented
안녕하세요 !

문서보고 마지막부분 프로세스 종료해두는거라고 생각하고 종료해뒀었습니다 😅
다시 확인부탁드립니다 !
감사합니다

2022-11-22 14:21 UTC, heowc requested changes
아직 dns 설정이 잘 되어 있는지 확인이 필요할 것 같아요~

또한, 몇가지 체크해야할 것들이 있는 것 같습니다.
1. 베스천 서버에서 타 서버 접근시 별도의 pem 사용해야 접근 가능
2. 감사로그, 이름 등등이 한 서버에만 적용되어 있음

다시 한번만 확인 부탁드릴게요 🙏

2022-11-23 15:08 UTC, iamsojung commented
다시 수정했습니다 !
확인부탁드립니다 !

2022-11-23 15:28 UTC, heowc approved these changes
피드백 반영 감사합니다 🙏 

다음 단계에서 진행 부탁드려요~

2022-11-23 15:28 UTC, merged