2단계 - 서비스 배포하기
next-step/infra-subway-deploy pull request #891
Opened 2022-11-20 06:30 UTC by cwJohnPark

안녕하세요! 태화님

2단계 서비스 배포하기 리뷰 부탁드립니다!

proxy 서버는 별도 인스턴스(`cwjohnpark-proxy`)에 생성해두었습니다.

감사합니다 😀

2022-11-21 01:04 UTC, wooobo requested changes
2단계 잘진행주셨네요!

몇가지 코멘트 남겨드렸는데 확인 후 재요청 부탁드려요~!

2022-11-21 01:04 UTC, wooobo commented on README.md
> +- URL: https://cwjonhpark-subway-px.o-r.kr
`proxy` 외부망 포트에 80포트는 제거해주세요.

2022-11-21 01:04 UTC, wooobo commented on README.md
> +- URL: https://cwjonhpark-subway-px.o-r.kr
HTTPS로 잘 연결되네요 🙏

2022-11-21 01:04 UTC, wooobo commented on README.md
> +- URL: https://cwjonhpark-subway-px.o-r.kr
![스크린샷 2022-11-21 오전 10 01 17](https://user-images.githubusercontent.com/12059592/202937270-f3a91f99-77fe-45b5-87e1-b8577c6e1eb4.png)

설정파일 나누기를 진행해보시면 좋을것 같아요 🙏 

`실제로 배포할 때 등 각 상황에 맞춰 설정을 다르게 적용할 필요성이 생깁니다.` 경험해보시면 좋을것 같아요!

2022-11-21 08:39 UTC, cwJohnPark commented on README.md
> +- URL: https://cwjonhpark-subway-px.o-r.kr
`src/main/resources/application-prd.properties`
에 생성해두었습니다!
기본적으로 DB가 h2 로 설정이 되어서 dev는 따로 생성하지 않았습니다.

2022-11-21 08:39 UTC, cwJohnPark commented on README.md
> +- URL: https://cwjonhpark-subway-px.o-r.kr
80포트 제거 완료하였습니다!

2022-11-22 00:46 UTC, wooobo approved these changes
2단계 잘 진행해주셨습니다!

이만 `merge` 진행하겠습니다~
다음단계 진행해주세요~

2022-11-22 00:46 UTC, merged