Step2 서비스 배포하기 리뷰 요청드립니다
next-step/infra-subway-deploy pull request #928
Opened 2022-11-23 03:12 UTC by paki1019

안녕하세요, Step2 서비스 배포하기 리뷰 요청드립니다!

- Step1 리뷰에서 EC2의 스펙 관련해서 코맨트 주셨었는데요, 강의 해주신 이동규님께서 ec2 권한에대해 아래와 같이 공지해주셔서 부득이하게 t3로 인스턴스를 띄웠었습니다..!(지금 와서 생각해보니 bastion 서버는 t4로 띄웠어도 됐을것 같네요 ㅎ)
> #11월 18일 공지
>  추가적으로, ec2 관련 권한을 일부 수정했는데요.
> 1. t4g -> t3 권한으로 변경해두었어요. t4g가 arm 기반이라 실습 컨테이너가 뜨지 않아서요. 다시 빌드하기엔 데이터 셋업하는데 시간이 걸려서 > 정책 바꿔뒀으니 참고바래요 (이미 t4g에서 내부망 서버 띄우신 분들은 중지하고 다시 생성 바래요~)

2022-11-23 14:31 UTC, dhmin5693 commented
그런 히스토리가 있었군요 ㅎㅎ;
거기까지는 공지되지 않아서 잘 몰랐었네요.
저번 피드백에서도 남겼듯 굳이 다시 띄우실 필요까지는 없었다고 생각하지만 학습을 위한 좋은 태도라고 생각됩니다 👏👏👏👏

2022-11-23 15:01 UTC, dhmin5693 requested changes
안녕하세요 진호님.
502 bad gateway 가 발생하고 있어서 다시 한번 확인 부탁드리겠습니다.
점검하신 후 다시 피드백 요청주세요.

2022-11-23 15:01 UTC, dhmin5693 commented on README.md
> +- URL : https://nextstep.paki1019.o-r.kr/
`502 bad gateway` 가 뜨며 접속이 안되고 있어요. 다시 한번 확인 부탁드립니다.

2022-11-23 15:01 UTC, dhmin5693 commented on src/main/resources/application-prod.yml
> +    password: masterpw
github는 공개된 공간입니다.
production 의 접속 정보는 숨겨주세요.

이 과정에선 RDS 등 AWS 서비스를 별도로 사용하지 않아서 해당되지 않지만 공개 환경에선 prod 접속정보 뿐만 아니라 AWS 관련 정보는 죄다 숨기는게 좋아요.
해킹당할 수 있거든요.

2022-11-23 15:01 UTC, dhmin5693 commented on src/main/resources/application-prod.yml
> +    password: masterpw
어짜피 확인해야할 것이 있으니 flyway도 한번 적용해보세요 :)

2022-11-23 15:01 UTC, dhmin5693 commented on README.md
> +- URL : https://nextstep.paki1019.o-r.kr/
nginx 확인을 위해 public을 접속하려 했는데요,
bastion -> public/internal 로 접근되지 않고 있습니다.

Permission denied (publickey) 가 발생하고 있어요.

2022-11-23 15:01 UTC, dhmin5693 commented on README.md
> +- URL : https://nextstep.paki1019.o-r.kr/
`nginx.conf` 에 설정된 도메인이 `nextstep.paki1019.o-r.kr` 와는 다르게 되어있네요.

2022-11-24 00:45 UTC, paki1019 commented on README.md
> +- URL : https://nextstep.paki1019.o-r.kr/
> `502 bad gateway` 가 뜨며 접속이 안되고 있어요. 다시 한번 확인 부탁드립니다.

백그라운드로 돌던 java 프로세스가 죽어서 `502 bad gateway`가 뜨고 있었습니다 ㅠ 터미널 세션이 끊기면서 같이 죽은게 문제인듯 하네요.. 이 부분을 보완하여 `hohup`으로 java 프로세스 띄우도록 개선하도록 하겠습니다.
```
nohup java -jar subway-0.0.1-SNAPSHOT.jar 1> nohub.log 2>&1  &
```
> nginx 확인을 위해 public을 접속하려 했는데요, bastion -> public/internal 로 접근되지 않고 있습니다.
> 
> Permission denied (publickey) 가 발생하고 있어요.

이부분은 재현이 안되고있는데요.. 혹시 해결되었을까요..? 바스티온 서버의 `access_public_ec2.sh`, `access_internal_ec2.sh`를 참고해주시면 될것같습니다..!

> `nginx.conf` 에 설정된 도메인이 `nextstep.paki1019.o-r.kr` 와는 다르게 되어있네요.
`nginx.conf`도 다른 부분을 확인안되고 있습니다.. 혹시 제가 놓친 부분 있으면 다시 말씀 한번 부탁드립니다..!
```
ssl_certificate /etc/letsencrypt/live/paki1019.o-r.kr/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/paki1019.o-r.kr/privkey.pem;
```

2022-11-24 14:33 UTC, paki1019 commented on src/main/resources/application-prod.yml
> +    password: masterpw
`jwt secret키`, `prod-db` 주소 와 같이 민감한 데이터들을 개인 private 레포로 격리시켜 보았습니다..!
컨피그 파일에서는 spring.config.import를 활용 별개 yml 파일을 import 하도록 구성해두었습니다..!

쉽진 않았지만... 성공적으로 flyway 적용 완료하였습니다!(좋은 경험이 되었습니다. ㅎ)
이미 존재하는 데이터들은 건들이기가 애매해서, `market`이라는 테스트용 테이블 생성, 컬럼 추가, 데이터를 insert 실습만 해보았습니다..!
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/12606910/203808024-ee71a66e-11f6-4ea3-b983-247b63b737d6.png">
> public, internel 서버에 mysql CLI 설치해두었습니다..!

2022-11-24 15:49 UTC, dhmin5693 commented on README.md
> +- URL : https://nextstep.paki1019.o-r.kr/
일단은 접속이 잘 되고 있네요.
nginx 설정 문제는 아니었군요.

강의 자료를 보면 도메인을 그대로 사용하라고 기재되어 있어요.
아래처럼 작성되는 것을 생각하고 있었거든요.

```
ssl_certificate /etc/letsencrypt/live/nextstep.paki1019.o-r.kr/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/nextstep.paki1019.o-r.kr/privkey.pem;
```

2022-11-24 15:50 UTC, dhmin5693 approved these changes
잘 작동되고 있네요 :)
확인이 완료되었으니 다음 미션 진행해주세요.

질문에 대한 답변도 남겨두었으니 같이 확인바랍니다.
수고하셨습니다. 🙇‍♂️

2022-11-24 15:50 UTC, dhmin5693 commented on src/main/resources/db/migration/R__add_market_data.sql
> +INSERT INTO market(name, address) values ("market1", "address1");
👍

2022-11-24 15:50 UTC, dhmin5693 commented on src/main/resources/application-prod.yml
> +spring:
가장 핵심 정보만 분리하셨네요. 좋습니다! 👍

2022-11-24 15:52 UTC, merged