2단계 - 서비스 배포하기
next-step/infra-subway-deploy pull request #935
Opened 2022-11-23 16:23 UTC by yomni

안녕하세요!
우선 이번에는 1단계에서 가볍게 피드백 주신
보안그룹에서 다른 보안그룹을 소스로 활용하여 설정하는 것을 적용했습니다.

2단계에선 제가 qna를 미처 확인 못하고, 질문주신분과 똑같은 실수를 범해서
amd64 인스턴스를 새롭게 생성하여 다시 설정하였습니다! 😭

리뷰 미리 감사드립니다 🙇🏻‍♂️

2022-11-24 12:41 UTC, minzzang requested changes
안녕하세요 용민님~!

그럴듯한 서비스 만들기 2단계 미션 잘 수행해주셨네요! 👍 

설정이 안된 부분이 있어 코멘트 남겼는데 확인 부탁드립니다. :pray:

그럼 오늘 하루도 화이팅입니다. :muscle:

2022-11-24 12:41 UTC, minzzang commented on README.md
> +#### 1단계 피드백
피드백 회고 좋네요 👍

2022-11-24 12:41 UTC, minzzang commented on README.md
> +    - [x] 외부망(public)에 `nginx`로 `Reverse Proxy`를 구성
외부망 서브넷이 2개인데 proxy server와 application server를 분리해봐도 좋을 것 같아요 😄

2022-11-24 12:41 UTC, minzzang commented on README.md
> +- URL : https://runningmap.kro.kr
TLS설정과 http -> https 리다이렉트 확인했습니다. 👍

2022-11-24 12:41 UTC, minzzang commented on src/main/resources/application-prod.properties
> +account.name=produser
운영 db가 연동이 안된 것 같아요! 연동하는 설정 확인 부탁드립니다. 😄 
그리고 password가 그대로 노출되는데 서브 모듈을 활용해서 분리해보면 어떨까요~?

2022-11-24 12:41 UTC, minzzang commented on src/main/resources/application-local.properties
> +account.name=localuser
요구사항에 맞게 local db도 설정 부탁드립니다~ 😄 
`JUnit : h2, Local : docker(mysql), Prod : 운영 DB를 사용`

2022-11-25 11:17 UTC, minzzang approved these changes
안녕하세요 용민님~!

피드백 잘 반영해주셨네요! 👍

소소한 코멘트 남겼는데 확인 부탁드립니다. 🙏

그럼 즐거운 금요일 보내세요~💪

2022-11-25 11:17 UTC, minzzang commented on src/main/resources/application-prod.yml
> +  jwt:
jwt토큰은 어디서 사용되는지 알 수 있을까요~?

2022-11-25 11:17 UTC, minzzang commented on src/main/resources/application-prod.yml
> +handlebars:
해당 설정을 추가해주신 이유가 있나요~?

2022-11-25 11:18 UTC, merged

2022-11-25 15:25 UTC, yomni commented on src/main/resources/application-prod.yml
> +  jwt:
jwt 토큰은 **_로그인 시 인증_**에 활용됩니다.
설정파일의 jwt secret-key는 jwt를 생성하기 위한 Key로 활용됩니다.
이걸 물어보시는게 맞는걸까요?..

2022-11-25 15:40 UTC, yomni commented on src/main/resources/application-prod.yml
> +handlebars:
handlebars는 템플릿 엔진으로 알고 있는데요.
현재 구현되어 있는 소스코드에서는 해당 설정을 추가하지 않으면, 초기 화면이 로딩되지 않습니다

혹시 제가 잘못설정한게 있는걸까요?.. 피드백 주시면 감사하겠습니다.