step2) 서비스 배포하기 리뷰 요청 드립니다!
next-step/infra-subway-deploy pull request #94
Opened 2021-06-19 16:14 UTC by limdingdong

수빈님 안녕하세요!
2단계 서비스 배포하기 실습결과 리뷰 요청드립니다~!

이번에도 역시 처음 접해보는 개념들이 많아서 시행착오를 많이 겪었네요😭
실습은 다 해보기는 했는데, 망 구성이나 이런 부분들이 좀 어색하실 수 있을 것 같습니다.

여유있으실 때 한 번 확인해주시면 감사하겠습니다
그럼 즐거운 주말 보내세요!😄

2021-06-20 10:54 UTC, tearight commented
안녕하세요. reverse-proxy 가 확인되지 않아 코멘트 드려요.
ec2 인스턴스에서 limdingdong 으로 검색시 reverse-proxy 용 서버가 보이지 않네요.
미션 요구사항에 reverse-proxy 구현이 있어 확인해주셔야 할 것 같습니다.

reverse-proxy 다른 서버의 환경 구성도 같이 바뀌어야 하는데요.
- reverse-proxy 도 bastion 서버를 통해서만 ssh 에 접속 가능해여야 한다.
- reverse-proxy 는 http, https 요청을 받아야 하며 http 요청시 https 로 redirect 되어야 한다.
- 기존 public server는 외부 접속이 막혀있어야 하고 reverse-proxy 서버로만 요청을 받을 수 있다.(8080포트만, 즉 TLS 설정은 reverse-proxy 만 진행)

이런 요구사항들이 있으니 확인 부탁드릴게요.

2021-06-20 10:55 UTC, tearight requested changes
안녕하세요, 설정은 잘 된 것으로 보이나 reverse-proxy 구성이 안된 것  같습니다.
미션을 한번 더 확인 부탁드릴게요.

2021-06-21 00:08 UTC, limdingdong commented
수빈님 안녕하세요!
가이드 주신부분 참고하여 reverse-proxy 를 위한 EC2 인스턴스를 새로 생성해 구성해 보았습니다!
친절하고 자세하게 설명해 주셔서 다시 차근차근 해 볼수가 있었습니다. 감사합니다!

제가 web 어플리케이션을 위한 EC2 인스턴스에 reverse proxy 를 같이 띄워놓았었네요😅
인프라를 다뤄본 경험이 없어서 갈피를 못잡고 막 되는대로 나가보았는데, 수빈님께서 보시기 번거로우셨을 것 같습니다😭

여유있으실 때 한 번 봐주시면 감사하겠습니다! 그럼 이번 주도 즐거운 한 주 보내세요~!

2021-06-21 12:29 UTC, tearight approved these changes
리버시 프록시 구성해주신 것을 확인했습니다.
요청이 의도하신대로 잘 들어가네요. 👍
미션은 이것으로 마치도록 하겠습니다. 다음 미션도 화이팅입니다!

2021-06-21 12:30 UTC, merged